In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("/home/sanjay/Project/Project100/Pandas-learning-projects/sales-data-analysis/data/sales.csv")

In [5]:
df.head()

df.tail()

df.info()

df.describe()

df.shape

df.columns

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   OrderID   12 non-null     int64
 1   Customer  12 non-null     str
 2   City      12 non-null     str
 3   Category  12 non-null     str
 4   Product   12 non-null     str
 5   Quantity  12 non-null     int64
 6   Price     12 non-null     int64
 7   Date      12 non-null     str
dtypes: int64(3), str(5)
memory usage: 900.0 bytes

Index(['OrderID', 'Customer', 'City', 'Category', 'Product', 'Quantity',
       'Price', 'Date'],
      dtype='str')

In [9]:
df.isnull().sum()

OrderID     0
Customer    0
City        0
Category    0
Product     0
Quantity    0
Price       0
Date        0
Revenue     0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [7]:
df["Revenue"] = df["Quantity"] * df["Price"]

In [8]:
df.head()

,OrderID,Customer,City,Category,Product,Quantity,Price,Date,Revenue
0,1001,Alice,Chennai,Electronics,Laptop,1,55000,2026-01-10,55000
1,1002,Bob,Coimbatore,Furniture,Chair,4,2500,2026-01-12,10000
2,1003,Charlie,Bangalore,Electronics,Mouse,3,700,2026-01-15,2100
3,1004,David,Chennai,Furniture,Table,2,8000,2026-01-18,16000
4,1005,Eva,Madurai,Electronics,Keyboard,5,1200,2026-01-19,6000

In [10]:
df.to_csv("output/sales_with_revenue.csv", index=False)

In [12]:
df[df["Category"] == "Electronics"]

,OrderID,Customer,City,Category,Product,Quantity,Price,Date,Revenue
0,1001,Alice,Chennai,Electronics,Laptop,1,55000,2026-01-10,55000
2,1003,Charlie,Bangalore,Electronics,Mouse,3,700,2026-01-15,2100
4,1005,Eva,Madurai,Electronics,Keyboard,5,1200,2026-01-19,6000
5,1006,Frank,Coimbatore,Electronics,Monitor,2,15000,2026-01-20,30000
7,1008,Henry,Chennai,Electronics,Headphones,6,2500,2026-01-24,15000
9,1010,Jack,Coimbatore,Electronics,Laptop,2,55000,2026-01-28,110000
11,1012,Liam,Bangalore,Electronics,Monitor,1,15000,2026-02-05,15000

In [13]:
df["Category"] == "Electronics"

0      True
1     False
2      True
3     False
4      True
5      True
6     False
7      True
8     False
9      True
10    False
11     True
Name: Category, dtype: bool

In [14]:
df[df["Price"] > 10000]

,OrderID,Customer,City,Category,Product,Quantity,Price,Date,Revenue
0,1001,Alice,Chennai,Electronics,Laptop,1,55000,2026-01-10,55000
5,1006,Frank,Coimbatore,Electronics,Monitor,2,15000,2026-01-20,30000
6,1007,Grace,Bangalore,Furniture,Sofa,1,35000,2026-01-22,35000
8,1009,Ivy,Madurai,Furniture,Cupboard,1,18000,2026-01-25,18000
9,1010,Jack,Coimbatore,Electronics,Laptop,2,55000,2026-01-28,110000
11,1012,Liam,Bangalore,Electronics,Monitor,1,15000,2026-02-05,15000

In [15]:
df[(df["Category"] == "Electronics") & (df["Price"] > 10000)]

,OrderID,Customer,City,Category,Product,Quantity,Price,Date,Revenue
0,1001,Alice,Chennai,Electronics,Laptop,1,55000,2026-01-10,55000
5,1006,Frank,Coimbatore,Electronics,Monitor,2,15000,2026-01-20,30000
9,1010,Jack,Coimbatore,Electronics,Laptop,2,55000,2026-01-28,110000
11,1012,Liam,Bangalore,Electronics,Monitor,1,15000,2026-02-05,15000

In [17]:
df[(df["City"] == "Chennai") | (df["City"] == "Bangalore")]

,OrderID,Customer,City,Category,Product,Quantity,Price,Date,Revenue
0,1001,Alice,Chennai,Electronics,Laptop,1,55000,2026-01-10,55000
2,1003,Charlie,Bangalore,Electronics,Mouse,3,700,2026-01-15,2100
3,1004,David,Chennai,Furniture,Table,2,8000,2026-01-18,16000
6,1007,Grace,Bangalore,Furniture,Sofa,1,35000,2026-01-22,35000
7,1008,Henry,Chennai,Electronics,Headphones,6,2500,2026-01-24,15000
10,1011,Kate,Chennai,Furniture,Chair,8,2500,2026-02-02,20000
11,1012,Liam,Bangalore,Electronics,Monitor,1,15000,2026-02-05,15000

In [18]:
df[
(df["City"]=="Chennai") |
(df["City"]=="Madurai") |
(df["City"]=="Bangalore")
]

,OrderID,Customer,City,Category,Product,Quantity,Price,Date,Revenue
0,1001,Alice,Chennai,Electronics,Laptop,1,55000,2026-01-10,55000
2,1003,Charlie,Bangalore,Electronics,Mouse,3,700,2026-01-15,2100
3,1004,David,Chennai,Furniture,Table,2,8000,2026-01-18,16000
4,1005,Eva,Madurai,Electronics,Keyboard,5,1200,2026-01-19,6000
6,1007,Grace,Bangalore,Furniture,Sofa,1,35000,2026-01-22,35000
7,1008,Henry,Chennai,Electronics,Headphones,6,2500,2026-01-24,15000
8,1009,Ivy,Madurai,Furniture,Cupboard,1,18000,2026-01-25,18000
10,1011,Kate,Chennai,Furniture,Chair,8,2500,2026-02-02,20000
11,1012,Liam,Bangalore,Electronics,Monitor,1,15000,2026-02-05,15000

In [19]:
df[df["City"].isin(["Chennai","Madurai","Bangalore"])]

,OrderID,Customer,City,Category,Product,Quantity,Price,Date,Revenue
0,1001,Alice,Chennai,Electronics,Laptop,1,55000,2026-01-10,55000
2,1003,Charlie,Bangalore,Electronics,Mouse,3,700,2026-01-15,2100
3,1004,David,Chennai,Furniture,Table,2,8000,2026-01-18,16000
4,1005,Eva,Madurai,Electronics,Keyboard,5,1200,2026-01-19,6000
6,1007,Grace,Bangalore,Furniture,Sofa,1,35000,2026-01-22,35000
7,1008,Henry,Chennai,Electronics,Headphones,6,2500,2026-01-24,15000
8,1009,Ivy,Madurai,Furniture,Cupboard,1,18000,2026-01-25,18000
10,1011,Kate,Chennai,Furniture,Chair,8,2500,2026-02-02,20000
11,1012,Liam,Bangalore,Electronics,Monitor,1,15000,2026-02-05,15000

In [20]:
df[(df["Price"]>=2000) & (df["Price"]<=20000)]

,OrderID,Customer,City,Category,Product,Quantity,Price,Date,Revenue
1,1002,Bob,Coimbatore,Furniture,Chair,4,2500,2026-01-12,10000
3,1004,David,Chennai,Furniture,Table,2,8000,2026-01-18,16000
5,1006,Frank,Coimbatore,Electronics,Monitor,2,15000,2026-01-20,30000
7,1008,Henry,Chennai,Electronics,Headphones,6,2500,2026-01-24,15000
8,1009,Ivy,Madurai,Furniture,Cupboard,1,18000,2026-01-25,18000
10,1011,Kate,Chennai,Furniture,Chair,8,2500,2026-02-02,20000
11,1012,Liam,Bangalore,Electronics,Monitor,1,15000,2026-02-05,15000

In [21]:
df[df["Price"].between(2000,20000)]

,OrderID,Customer,City,Category,Product,Quantity,Price,Date,Revenue
1,1002,Bob,Coimbatore,Furniture,Chair,4,2500,2026-01-12,10000
3,1004,David,Chennai,Furniture,Table,2,8000,2026-01-18,16000
5,1006,Frank,Coimbatore,Electronics,Monitor,2,15000,2026-01-20,30000
7,1008,Henry,Chennai,Electronics,Headphones,6,2500,2026-01-24,15000
8,1009,Ivy,Madurai,Furniture,Cupboard,1,18000,2026-01-25,18000
10,1011,Kate,Chennai,Furniture,Chair,8,2500,2026-02-02,20000
11,1012,Liam,Bangalore,Electronics,Monitor,1,15000,2026-02-05,15000

In [22]:
df.sort_values("Price", ascending=False)

,OrderID,Customer,City,Category,Product,Quantity,Price,Date,Revenue
0,1001,Alice,Chennai,Electronics,Laptop,1,55000,2026-01-10,55000
9,1010,Jack,Coimbatore,Electronics,Laptop,2,55000,2026-01-28,110000
6,1007,Grace,Bangalore,Furniture,Sofa,1,35000,2026-01-22,35000
8,1009,Ivy,Madurai,Furniture,Cupboard,1,18000,2026-01-25,18000
11,1012,Liam,Bangalore,Electronics,Monitor,1,15000,2026-02-05,15000
5,1006,Frank,Coimbatore,Electronics,Monitor,2,15000,2026-01-20,30000
3,1004,David,Chennai,Furniture,Table,2,8000,2026-01-18,16000
1,1002,Bob,Coimbatore,Furniture,Chair,4,2500,2026-01-12,10000
10,1011,Kate,Chennai,Furniture,Chair,8,2500,2026-02-02,20000
7,1008,Henry,Chennai,Electronics,Headphones,6,2500,2026-01-24,15000
4,1005,Eva,Madurai,Electronics,Keyboard,5,1200,2026-01-19,6000
2,1003,Charlie,Bangalore,Electronics,Mouse,3,700,2026-01-15,2100

In [23]:
df.sort_values("Price")

,OrderID,Customer,City,Category,Product,Quantity,Price,Date,Revenue
2,1003,Charlie,Bangalore,Electronics,Mouse,3,700,2026-01-15,2100
4,1005,Eva,Madurai,Electronics,Keyboard,5,1200,2026-01-19,6000
7,1008,Henry,Chennai,Electronics,Headphones,6,2500,2026-01-24,15000
1,1002,Bob,Coimbatore,Furniture,Chair,4,2500,2026-01-12,10000
10,1011,Kate,Chennai,Furniture,Chair,8,2500,2026-02-02,20000
3,1004,David,Chennai,Furniture,Table,2,8000,2026-01-18,16000
11,1012,Liam,Bangalore,Electronics,Monitor,1,15000,2026-02-05,15000
5,1006,Frank,Coimbatore,Electronics,Monitor,2,15000,2026-01-20,30000
8,1009,Ivy,Madurai,Furniture,Cupboard,1,18000,2026-01-25,18000
6,1007,Grace,Bangalore,Furniture,Sofa,1,35000,2026-01-22,35000
0,1001,Alice,Chennai,Electronics,Laptop,1,55000,2026-01-10,55000
9,1010,Jack,Coimbatore,Electronics,Laptop,2,55000,2026-01-28,110000

In [24]:
df.sort_values("Revenue", ascending=False)

,OrderID,Customer,City,Category,Product,Quantity,Price,Date,Revenue
9,1010,Jack,Coimbatore,Electronics,Laptop,2,55000,2026-01-28,110000
0,1001,Alice,Chennai,Electronics,Laptop,1,55000,2026-01-10,55000
6,1007,Grace,Bangalore,Furniture,Sofa,1,35000,2026-01-22,35000
5,1006,Frank,Coimbatore,Electronics,Monitor,2,15000,2026-01-20,30000
10,1011,Kate,Chennai,Furniture,Chair,8,2500,2026-02-02,20000
8,1009,Ivy,Madurai,Furniture,Cupboard,1,18000,2026-01-25,18000
3,1004,David,Chennai,Furniture,Table,2,8000,2026-01-18,16000
7,1008,Henry,Chennai,Electronics,Headphones,6,2500,2026-01-24,15000
11,1012,Liam,Bangalore,Electronics,Monitor,1,15000,2026-02-05,15000
1,1002,Bob,Coimbatore,Furniture,Chair,4,2500,2026-01-12,10000
4,1005,Eva,Madurai,Electronics,Keyboard,5,1200,2026-01-19,6000
2,1003,Charlie,Bangalore,Electronics,Mouse,3,700,2026-01-15,2100

In [25]:
df.sort_values("Price", ascending=False).head(5)

,OrderID,Customer,City,Category,Product,Quantity,Price,Date,Revenue
0,1001,Alice,Chennai,Electronics,Laptop,1,55000,2026-01-10,55000
9,1010,Jack,Coimbatore,Electronics,Laptop,2,55000,2026-01-28,110000
6,1007,Grace,Bangalore,Furniture,Sofa,1,35000,2026-01-22,35000
8,1009,Ivy,Madurai,Furniture,Cupboard,1,18000,2026-01-25,18000
11,1012,Liam,Bangalore,Electronics,Monitor,1,15000,2026-02-05,15000

In [26]:
df.nlargest(5, "Price")

,OrderID,Customer,City,Category,Product,Quantity,Price,Date,Revenue
0,1001,Alice,Chennai,Electronics,Laptop,1,55000,2026-01-10,55000
9,1010,Jack,Coimbatore,Electronics,Laptop,2,55000,2026-01-28,110000
6,1007,Grace,Bangalore,Furniture,Sofa,1,35000,2026-01-22,35000
8,1009,Ivy,Madurai,Furniture,Cupboard,1,18000,2026-01-25,18000
5,1006,Frank,Coimbatore,Electronics,Monitor,2,15000,2026-01-20,30000

In [27]:
df.nsmallest(3, "Price")

,OrderID,Customer,City,Category,Product,Quantity,Price,Date,Revenue
2,1003,Charlie,Bangalore,Electronics,Mouse,3,700,2026-01-15,2100
4,1005,Eva,Madurai,Electronics,Keyboard,5,1200,2026-01-19,6000
1,1002,Bob,Coimbatore,Furniture,Chair,4,2500,2026-01-12,10000

In [30]:
df.groupby("City")["Revenue"].sum()

City
Bangalore      52100
Chennai       106000
Coimbatore    150000
Madurai        24000
Name: Revenue, dtype: int64

In [31]:
df.groupby("Category")["Revenue"].sum()

Category
Electronics    233100
Furniture       99000
Name: Revenue, dtype: int64

In [32]:
df.groupby("Category")["Price"].mean()

Category
Electronics    20628.571429
Furniture      13200.000000
Name: Price, dtype: float64

In [33]:
df.groupby("Category")["Quantity"].sum()

Category
Electronics    20
Furniture      16
Name: Quantity, dtype: int64

In [36]:
df.groupby("Customer")["Revenue"].sum()

Customer
Alice       55000
Bob         10000
Charlie      2100
David       16000
Eva          6000
Frank       30000
Grace       35000
Henry       15000
Ivy         18000
Jack       110000
Kate        20000
Liam        15000
Name: Revenue, dtype: int64

In [37]:
df.groupby("Customer")["Revenue"].sum().sort_values(ascending=False)

Customer
Jack       110000
Alice       55000
Grace       35000
Frank       30000
Kate        20000
Ivy         18000
David       16000
Henry       15000
Liam        15000
Bob         10000
Eva          6000
Charlie      2100
Name: Revenue, dtype: int64

In [38]:
df.groupby("Customer")["Revenue"].sum().idxmax()

'Jack'

In [39]:
df.groupby("City")["Revenue"].sum().idxmax()

'Coimbatore'

In [40]:
df.groupby("Category")["Price"].agg(["mean","max","min"])

                     mean    max   min
Category
Electronics  20628.571429  55000   700
Furniture    13200.000000  35000  2500

In [41]:
df.groupby("City")["Revenue"].agg(
    ["sum","mean","max","min"]
)

               sum          mean     max    min
City
Bangalore    52100  17366.666667   35000   2100
Chennai     106000  26500.000000   55000  15000
Coimbatore  150000  50000.000000  110000  10000
Madurai      24000  12000.000000   18000   6000

In [42]:
city_sales = df.groupby("City")["Revenue"].sum().reset_index()

In [43]:
city_sales.to_csv(
    "output/city_sales_report.csv",
    index=False
)