In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/transactions.csv")

In [3]:
df.shape

(100000, 7)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   TransactionID  100000 non-null  int64
 1   CustomerID     100000 non-null  int64
 2   City           100000 non-null  str
 3   Category       100000 non-null  str
 4   Quantity       100000 non-null  int64
 5   Price          100000 non-null  int64
 6   Revenue        100000 non-null  int64
dtypes: int64(5), str(2)
memory usage: 5.3 MB

In [5]:
df.memory_usage(deep=True)

Index                132
TransactionID     800000
CustomerID        800000
City             5682992
Category         5679627
Quantity          800000
Price             800000
Revenue           800000
dtype: int64

In [6]:
df.memory_usage(deep=True).sum()

np.int64(15362751)

In [7]:
df.memory_usage(deep=True).sum() / (1024 ** 2)

np.float64(14.651061058044434)

In [8]:
df_small = pd.read_csv(
    "data/transactions.csv",
    usecols=[
        "City",
        "Category",
        "Quantity",
        "Revenue"
    ]
)

In [9]:
df_small.head()

        City  Category  Quantity  Revenue
0  Hyderabad    Sports         5   129815
1    Madurai    Sports         1    91935
2    Madurai    Sports         9    25596
3  Bangalore     Books         4   214316
4  Bangalore  Clothing         2    30926

In [10]:
df_small = pd.read_csv(
    "data/transactions.csv",
    usecols=[
        "City",
        "Category",
        "Quantity",
        "Revenue"
    ],
    dtype={
        "City": "category",
        "Category": "category",
        "Quantity": "int8",
        "Revenue": "int64"
    }
)

In [11]:
df.memory_usage(deep=True).sum() / (1024 ** 2)

np.float64(14.651061058044434)

In [12]:
df_small.memory_usage(deep=True).sum() / (1024 ** 2)

np.float64(1.0500917434692383)

In [13]:
df[df["Revenue"] > 50000]

,TransactionID,CustomerID,City,Category,Quantity,Price,Revenue
0,1,4174,Hyderabad,Sports,5,25963,129815
1,2,4507,Madurai,Sports,1,91935,91935
3,4,2294,Bangalore,Books,4,53579,214316
6,7,4772,Salem,Clothing,3,35939,107817
8,9,2638,Hyderabad,Sports,4,35118,140472
...,...,...,...,...,...,...,...
99994,99995,1836,Coimbatore,Sports,4,65106,260424
99995,99996,2149,Madurai,Books,2,75864,151728
99996,99997,3559,Coimbatore,Electronics,4,75138,300552
99997,99998,3177,Madurai,Sports,3,58377,175131
99998,99999,3755,Madurai,Electronics,5,10981,54905

In [14]:
df.query("Revenue > 50000")

,TransactionID,CustomerID,City,Category,Quantity,Price,Revenue
0,1,4174,Hyderabad,Sports,5,25963,129815
1,2,4507,Madurai,Sports,1,91935,91935
3,4,2294,Bangalore,Books,4,53579,214316
6,7,4772,Salem,Clothing,3,35939,107817
8,9,2638,Hyderabad,Sports,4,35118,140472
...,...,...,...,...,...,...,...
99994,99995,1836,Coimbatore,Sports,4,65106,260424
99995,99996,2149,Madurai,Books,2,75864,151728
99996,99997,3559,Coimbatore,Electronics,4,75138,300552
99997,99998,3177,Madurai,Sports,3,58377,175131
99998,99999,3755,Madurai,Electronics,5,10981,54905

In [15]:
df.query(
    "Revenue > 50000 and Quantity >= 5"
)

,TransactionID,CustomerID,City,Category,Quantity,Price,Revenue
0,1,4174,Hyderabad,Sports,5,25963,129815
12,13,1330,Coimbatore,Sports,5,13190,65950
17,18,3919,Hyderabad,Furniture,8,82819,662552
18,19,4735,Hyderabad,Furniture,8,59343,474744
21,22,4380,Coimbatore,Sports,5,32579,162895
...,...,...,...,...,...,...,...
99988,99989,3178,Madurai,Books,6,12372,74232
99989,99990,4805,Chennai,Sports,5,25019,125095
99991,99992,1222,Bangalore,Furniture,9,29778,268002
99992,99993,3362,Salem,Books,6,95035,570210
99998,99999,3755,Madurai,Electronics,5,10981,54905

In [16]:
df.query(
    "City == 'Chennai' and Revenue > 100000"
)

,TransactionID,CustomerID,City,Category,Quantity,Price,Revenue
25,26,4485,Chennai,Furniture,7,79782,558474
41,42,3558,Chennai,Furniture,8,74410,595280
51,52,4005,Chennai,Electronics,2,91200,182400
71,72,3041,Chennai,Furniture,2,51062,102124
76,77,2363,Chennai,Books,3,44372,133116
...,...,...,...,...,...,...,...
99945,99946,4046,Chennai,Clothing,7,89426,625982
99952,99953,1101,Chennai,Electronics,8,64628,517024
99968,99969,3015,Chennai,Furniture,2,79368,158736
99981,99982,4932,Chennai,Books,6,74932,449592
99989,99990,4805,Chennai,Sports,5,25019,125095

In [17]:
df = pd.read_csv("data/transactions.csv")

In [18]:
chunks = pd.read_csv(
    "data/transactions.csv",
    chunksize=10000
)

In [19]:
first_chunk = next(chunks)

In [20]:
first_chunk.shape

(10000, 7)

In [21]:
first_chunk.head()

   TransactionID  CustomerID       City  Category  Quantity  Price  Revenue
0              1        4174  Hyderabad    Sports         5  25963   129815
1              2        4507    Madurai    Sports         1  91935    91935
2              3        1860    Madurai    Sports         9   2844    25596
3              4        2294  Bangalore     Books         4  53579   214316
4              5        2130  Bangalore  Clothing         2  15463    30926

In [22]:
for chunk in pd.read_csv(
    "data/transactions.csv",
    chunksize=10000
):
    print(chunk.shape)

(10000, 7)
(10000, 7)
(10000, 7)
(10000, 7)
(10000, 7)
(10000, 7)
(10000, 7)
(10000, 7)
(10000, 7)
(10000, 7)

In [23]:
total_rows = 0

for chunk in pd.read_csv(
    "data/transactions.csv",
    chunksize=10000
):
    total_rows += len(chunk)

print(total_rows)

100000

In [24]:
total_revenue = 0

for chunk in pd.read_csv(
    "data/transactions.csv",
    chunksize=10000
):
    total_revenue += chunk["Revenue"].sum()

print(total_revenue)

24942745465

In [25]:
category_revenue = {}

In [26]:
for chunk in pd.read_csv(
    "data/transactions.csv",
    chunksize=10000
):

    grouped = chunk.groupby("Category")["Revenue"].sum()

    for category, revenue in grouped.items():

        if category not in category_revenue:
            category_revenue[category] = 0

        category_revenue[category] += revenue

In [27]:
category_revenue

{'Books': 5013005776,
 'Clothing': 4964818675,
 'Electronics': 4992821723,
 'Furniture': 5000058171,
 'Sports': 4972041120}

In [28]:
category_sales = pd.DataFrame(
    list(category_revenue.items()),
    columns=["Category", "Revenue"]
)

In [29]:
category_sales

      Category     Revenue
0        Books  5013005776
1     Clothing  4964818675
2  Electronics  4992821723
3    Furniture  5000058171
4       Sports  4972041120

In [30]:
category_sales = category_sales.sort_values(
    "Revenue",
    ascending=False
)

In [31]:
category_sales.to_csv(
    "output/category_sales.csv",
    index=False
)

In [32]:
city_revenue = {}

for chunk in pd.read_csv(
    "data/transactions.csv",
    chunksize=10000
):

    grouped = chunk.groupby("City")["Revenue"].sum()

    for city, revenue in grouped.items():

        if city not in city_revenue:
            city_revenue[city] = 0

        city_revenue[city] += revenue

In [33]:
city_sales = pd.DataFrame(
    list(city_revenue.items()),
    columns=["City", "Revenue"]
)

In [34]:
city_sales = city_sales.sort_values(
    "Revenue",
    ascending=False
)

In [35]:
city_sales.to_csv(
    "output/city_sales.csv",
    index=False
)

In [36]:
customer_revenue = {}

for chunk in pd.read_csv(
    "data/transactions.csv",
    chunksize=10000
):

    grouped = chunk.groupby("CustomerID")["Revenue"].sum()

    for customer, revenue in grouped.items():

        if customer not in customer_revenue:
            customer_revenue[customer] = 0

        customer_revenue[customer] += revenue

In [37]:
customer_summary = pd.DataFrame(
    list(customer_revenue.items()),
    columns=["CustomerID", "TotalRevenue"]
)

In [38]:
customer_summary = customer_summary.sort_values(
    "TotalRevenue",
    ascending=False
)

In [39]:
top_customers = customer_summary.head(10)

In [40]:
top_customers

      CustomerID  TotalRevenue
1145        2238      13491182
2933        4204      12952330
521         1574      12591715
1674        2823      12478777
2655        3896      12406995
1186        2284      12280381
2358        3575      12078916
2848        4110      11841611
1758        2914      11834999
3401        4719      11529004

In [41]:
top_customers.to_csv(
    "output/customer_summary.csv",
    index=False
)

In [42]:
category_results = []

for chunk in pd.read_csv(
    "data/transactions.csv",
    chunksize=10000
):

    result = (
        chunk
        .groupby("Category")["Revenue"]
        .sum()
    )

    category_results.append(result)

In [43]:
category_results

[Category
 Books          495237983
 Clothing       502992867
 Electronics    522696510
 Furniture      511380561
 Sports         497206707
 Name: Revenue, dtype: int64,
 Category
 Books          499655867
 Clothing       493755065
 Electronics    493432726
 Furniture      480508558
 Sports         485191029
 Name: Revenue, dtype: int64,
 Category
 Books          496919520
 Clothing       497553169
 Electronics    529420356
 Furniture      494155507
 Sports         485092154
 Name: Revenue, dtype: int64,
 Category
 Books          514689294
 Clothing       508385702
 Electronics    477087293
 Furniture      500005554
 Sports         517509284
 Name: Revenue, dtype: int64,
 Category
 Books          508645973
 Clothing       485143909
 Electronics    474567749
 Furniture      531302878
 Sports         493224195
 Name: Revenue, dtype: int64,
 Category
 Books          514111896
 Clothing       487701739
 Electronics    501471752
 Furniture      481615727
 Sports         485051221
 Name: Revenue, dtype: int64,
 Category
 Books          476856185
 Clothing       519090364
 Electronics    495252430
 Furniture      512116284
 Sports         508252355
 Name: Revenue, dtype: int64,
 Category
 Books          490943143
 Clothing       496215153
 Electronics    477555841
 Furniture      498412895
 Sports         506400514
 Name: Revenue, dtype: int64,
 Category
 Books          503651268
 Clothing       478000127
 Electronics    506248798
 Furniture      498815063
 Sports         501467877
 Name: Revenue, dtype: int64,
 Category
 Books          512294647
 Clothing       495980580
 Electronics    515088268
 Furniture      491745144
 Sports         492645784
 Name: Revenue, dtype: int64]

In [44]:
category_combined = pd.concat(
    category_results
)

In [45]:
final_category_sales = (
    category_combined
    .groupby(level=0)
    .sum()
)

In [46]:
final_category_sales = (
    final_category_sales
    .reset_index()
)

In [47]:
final_category_sales.columns = [
    "Category",
    "Revenue"
]

In [48]:
for chunk in pd.read_csv(
    "data/transactions.csv",
    chunksize=10000
):

    memory = (
        chunk.memory_usage(deep=True).sum()
        / (1024 ** 2)
    )

    print(
        f"Chunk memory: {memory:.2f} MB"
    )

Chunk memory: 1.47 MB
Chunk memory: 1.47 MB
Chunk memory: 1.47 MB
Chunk memory: 1.47 MB
Chunk memory: 1.47 MB
Chunk memory: 1.47 MB
Chunk memory: 1.47 MB
Chunk memory: 1.47 MB
Chunk memory: 1.47 MB
Chunk memory: 1.47 MB

In [49]:
import pandas as pd

FILE_PATH = "data/transactions.csv"
CHUNK_SIZE = 10_000
def analyze_transactions(file_path, chunk_size):

    total_transactions = 0
    total_revenue = 0

    category_results = []
    city_results = []
    customer_results = []

    for chunk in pd.read_csv(
        file_path,
        chunksize=chunk_size
    ):

        total_transactions += len(chunk)

        total_revenue += chunk["Revenue"].sum()

        category_results.append(
            chunk.groupby("Category")["Revenue"].sum()
        )

        city_results.append(
            chunk.groupby("City")["Revenue"].sum()
        )

        customer_results.append(
            chunk.groupby("CustomerID")["Revenue"].sum()
        )

    return (
        total_transactions,
        total_revenue,
        category_results,
        city_results,
        customer_results
    )

In [50]:
results = analyze_transactions(
    FILE_PATH,
    CHUNK_SIZE
)

In [51]:
(
    total_transactions,
    total_revenue,
    category_results,
    city_results,
    customer_results
) = results

In [52]:
print(
    "Total Transactions:",
    total_transactions
)

print(
    "Total Revenue:",
    total_revenue
)

Total Transactions: 100000
Total Revenue: 24942745465

In [53]:
category_sales = pd.concat(
    category_results
)

In [54]:
category_sales = (
    category_sales
    .groupby(level=0)
    .sum()
    .reset_index()
)

In [55]:
category_sales.columns = [
    "Category",
    "Revenue"
]

In [56]:
category_sales = category_sales.sort_values(
    "Revenue",
    ascending=False
)

In [57]:
print(category_sales)

      Category     Revenue
0        Books  5013005776
3    Furniture  5000058171
2  Electronics  4992821723
4       Sports  4972041120
1     Clothing  4964818675

In [58]:
category_sales["RevenuePercentage"] = (
    category_sales["Revenue"]
    / total_revenue
    * 100
)

In [59]:
category_sales["RevenuePercentage"] = (
    category_sales["RevenuePercentage"]
    .round(2)
)

In [60]:
category_sales.to_csv(
    "output/category_sales.csv",
    index=False
)

In [61]:
city_sales = pd.concat(
    city_results
)

In [62]:
city_sales = (
    city_sales
    .groupby(level=0)
    .sum()
    .reset_index()
)

In [63]:
city_sales.columns = [
    "City",
    "Revenue"
]

In [64]:
city_sales = city_sales.sort_values(
    "Revenue",
    ascending=False
)

In [65]:
city_sales["RevenuePercentage"] = (
    city_sales["Revenue"]
    / total_revenue
    * 100
).round(2)

In [66]:
city_sales.to_csv(
    "output/city_sales.csv",
    index=False
)

In [67]:
customer_sales = pd.concat(
    customer_results
)

In [68]:
customer_sales = (
    customer_sales
    .groupby(level=0)
    .sum()
    .reset_index()
)

In [69]:
customer_sales.columns = [
    "CustomerID",
    "TotalRevenue"
]

In [70]:
customer_sales = customer_sales.sort_values(
    "TotalRevenue",
    ascending=False
)

In [71]:
top_customers = customer_sales.head(10)

In [73]:
print(top_customers)

      CustomerID  TotalRevenue
1238        2238      13491182
3204        4204      12952330
574         1574      12591715
1823        2823      12478777
2896        3896      12406995
1284        2284      12280381
2575        3575      12078916
3110        4110      11841611
1914        2914      11834999
3719        4719      11529004

In [74]:
top_customers.to_csv(
    "output/customer_summary.csv",
    index=False
)

In [75]:
high_value_count = 0

In [76]:
for chunk in pd.read_csv(
    FILE_PATH,
    chunksize=CHUNK_SIZE
):

    high_value_count += (
        chunk["Revenue"] > 100000
    ).sum()

In [77]:
print(
    "High-value transactions:",
    high_value_count
)

High-value transactions: 68501

In [78]:
highest_transaction = None

In [79]:
for chunk in pd.read_csv(
    FILE_PATH,
    chunksize=CHUNK_SIZE
):

    current_max = chunk["Revenue"].max()

    if (
        highest_transaction is None
        or current_max > highest_transaction
    ):
        highest_transaction = current_max

In [80]:
print(
    "Highest transaction:",
    highest_transaction
)

Highest transaction: 899991

In [81]:
average_revenue = (
    total_revenue /
    total_transactions
)

In [82]:
print(
    "Average transaction revenue:",
    round(average_revenue, 2)
)

Average transaction revenue: 249427.45

In [83]:
summary = pd.DataFrame({
    "Metric": [
        "Total Transactions",
        "Total Revenue",
        "Average Transaction Revenue",
        "Highest Transaction",
        "High Value Transactions"
    ],

    "Value": [
        total_transactions,
        total_revenue,
        round(average_revenue, 2),
        highest_transaction,
        high_value_count
    ]
})

In [84]:
summary

                        Metric         Value
0           Total Transactions  1.000000e+05
1                Total Revenue  2.494275e+10
2  Average Transaction Revenue  2.494275e+05
3          Highest Transaction  8.999910e+05
4      High Value Transactions  6.850100e+04

In [85]:
summary.to_csv(
    "output/summary.csv",
    index=False
)