In [1]:
import pandas as pd

In [8]:
customers = pd.read_csv("data/customer.csv")

products = pd.read_csv("data/product.csv")

orders = pd.read_csv("data/order.csv")

In [9]:
customers.head()

  CustomerID CustomerName        City
0       C101        Alice     Chennai
1       C102          Bob  Coimbatore
2       C103      Charlie   Bangalore
3       C104        David     Madurai
4       C105          Eva     Chennai

In [10]:
products.head()

  ProductID ProductName     Category  Price
0      P201      Laptop  Electronics  55000
1      P202       Mouse  Electronics    700
2      P203       Chair    Furniture   2500
3      P204     Monitor  Electronics  15000
4      P205       Table    Furniture   8000

In [11]:
orders.head()

   OrderID CustomerID ProductID  Quantity
0     1001       C101      P201         1
1     1002       C102      P203         4
2     1003       C103      P202         2
3     1004       C101      P204         1
4     1005       C105      P205         2

In [12]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    5 non-null      str
 1   CustomerName  5 non-null      str
 2   City          5 non-null      str
dtypes: str(3)
memory usage: 252.0 bytes

In [13]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ProductID    5 non-null      str
 1   ProductName  5 non-null      str
 2   Category     5 non-null      str
 3   Price        5 non-null      int64
dtypes: int64(1), str(3)
memory usage: 292.0 bytes

In [14]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     8 non-null      int64
 1   CustomerID  8 non-null      str
 2   ProductID   8 non-null      str
 3   Quantity    8 non-null      int64
dtypes: int64(2), str(2)
memory usage: 388.0 bytes

In [15]:
orders_customers = pd.merge(
    orders,
    customers,
    on="CustomerID"
)

In [16]:
sales = pd.merge(
    orders_customers,
    products,
    on="ProductID"
)

In [17]:
sales.head()

,OrderID,CustomerID,ProductID,Quantity,CustomerName,City,ProductName,Category,Price
0,1001,C101,P201,1,Alice,Chennai,Laptop,Electronics,55000
1,1002,C102,P203,4,Bob,Coimbatore,Chair,Furniture,2500
2,1003,C103,P202,2,Charlie,Bangalore,Mouse,Electronics,700
3,1004,C101,P204,1,Alice,Chennai,Monitor,Electronics,15000
4,1005,C105,P205,2,Eva,Chennai,Table,Furniture,8000

In [18]:
sales["Revenue"] = (
    sales["Quantity"] *
    sales["Price"]
)

In [19]:
sales.to_csv(
    "output/sales_report.csv",
    index=False
)

In [25]:
inner_join = pd.merge(
    orders,
    customers,
    on="CustomerID",
    how="inner"
)

In [26]:
left_join = pd.merge(
    orders,
    customers,
    on="CustomerID",
    how="left"
)

In [27]:
right_join = pd.merge(
    orders,
    customers,
    on="CustomerID",
    how="right"
)

In [28]:
outer_join = pd.merge(
    orders,
    customers,
    on="CustomerID",
    how="outer"
)

In [29]:
print(inner_join.shape)

print(left_join.shape)

print(right_join.shape)

print(outer_join.shape)

(8, 6)
(8, 6)
(8, 6)
(8, 6)

In [30]:
inner_join.to_csv("output/inner_join.csv", index=False)

left_join.to_csv("output/left_join.csv", index=False)

right_join.to_csv("output/right_join.csv", index=False)

outer_join.to_csv("output/outer_join.csv", index=False)

In [31]:
merge_check = pd.merge(
    orders,
    customers,
    on="CustomerID",
    how="outer",
    indicator=True
)

In [32]:
orders2 = orders.rename(columns={"CustomerID": "Cust_ID"})

In [33]:
orders2.head()

   OrderID Cust_ID ProductID  Quantity
0     1001    C101      P201         1
1     1002    C102      P203         4
2     1003    C103      P202         2
3     1004    C101      P204         1
4     1005    C105      P205         2

In [34]:
merge_demo = pd.merge(
    orders2,
    customers,
    left_on="Cust_ID",
    right_on="CustomerID"
)

In [35]:
merged = pd.merge(
    orders,
    customers,
    on="CustomerID",
    suffixes=("_Order", "_Customer")
)

In [36]:
orders_customers = pd.merge(
    orders,
    customers,
    on="CustomerID"
)

In [37]:
sales = pd.merge(
    orders_customers,
    products,
    on="ProductID"
)

In [38]:
sales["Revenue"] = (
    sales["Quantity"] *
    sales["Price"]
)

In [39]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       8 non-null      int64
 1   CustomerID    8 non-null      str
 2   ProductID     8 non-null      str
 3   Quantity      8 non-null      int64
 4   CustomerName  8 non-null      str
 5   City          8 non-null      str
 6   ProductName   8 non-null      str
 7   Category      8 non-null      str
 8   Price         8 non-null      int64
 9   Revenue       8 non-null      int64
dtypes: int64(4), str(6)
memory usage: 772.0 bytes

In [40]:
sales.groupby("CustomerName")["Revenue"].sum()

CustomerName
Alice      70000
Bob        25000
Charlie    56400
David      15000
Eva        16000
Name: Revenue, dtype: int64

In [41]:
sales.groupby("CustomerName")["Revenue"].sum()

CustomerName
Alice      70000
Bob        25000
Charlie    56400
David      15000
Eva        16000
Name: Revenue, dtype: int64

In [42]:
sales.groupby("Category")["Revenue"].sum()

Category
Electronics    141400
Furniture       41000
Name: Revenue, dtype: int64

In [43]:
sales.groupby("ProductName")["Quantity"].sum()

ProductName
Chair      10
Laptop      2
Monitor     2
Mouse       2
Table       2
Name: Quantity, dtype: int64

In [44]:
sales.groupby("CustomerName")["Revenue"].sum().idxmax()

'Alice'

In [45]:
sales.to_csv(
    "output/final_business_report.csv",
    index=False
)