In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/daily_sales.csv")

In [3]:
df.head()

         Date  Product     Category  Sales
0  2026-01-01   Laptop  Electronics  55000
1  2026-01-02    Mouse  Electronics   2100
2  2026-01-03    Chair    Furniture  10000
3  2026-01-04  Monitor  Electronics  30000
4  2026-01-05    Table    Furniture  16000

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      15 non-null     str
 1   Product   15 non-null     str
 2   Category  15 non-null     str
 3   Sales     15 non-null     int64
dtypes: int64(1), str(3)
memory usage: 612.0 bytes

In [5]:
df.describe()

               Sales
count      15.000000
mean    27066.666667
std     28759.536721
min      1400.000000
25%      9000.000000
50%     15000.000000
75%     35000.000000
max    110000.000000

In [9]:
df.dtypes

Date          str
Product       str
Category      str
Sales       int64
dtype: object

In [11]:
df["Date"] = pd.to_datetime(df["Date"])

In [12]:
df.dtypes

Date        datetime64[us]
Product                str
Category               str
Sales                int64
dtype: object

In [ ]:
df["Year"] = df["Date"].dt.year

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (1004570245.py, line 1)

In [14]:
df["Month"] = df["Date"].dt.month

In [15]:
df["Day"] = df["Date"].dt.day

In [16]:
df["DayName"] = df["Date"].dt.day_name()

In [18]:
df[df["Date"] > "2026-01-05"]

         Date   Product     Category   Sales  Year  Month  Day    DayName
5  2026-01-06    Laptop  Electronics  110000  2026      1    6    Tuesday
6  2026-01-07  Keyboard  Electronics    6000  2026      1    7  Wednesday
7  2026-01-08      Sofa    Furniture   35000  2026      1    8   Thursday
8  2026-01-09   Monitor  Electronics   15000  2026      1    9     Friday
9  2026-01-10     Chair    Furniture   12500  2026      1   10   Saturday
10 2026-01-11    Laptop  Electronics   55000  2026      1   11     Sunday
11 2026-01-12     Mouse  Electronics    1400  2026      1   12     Monday
12 2026-01-13     Table    Furniture    8000  2026      1   13    Tuesday
13 2026-01-14   Monitor  Electronics   15000  2026      1   14  Wednesday
14 2026-01-15      Sofa    Furniture   35000  2026      1   15   Thursday

In [19]:
df[df["Date"] < "2026-01-10"]

        Date   Product     Category   Sales  Year  Month  Day    DayName
0 2026-01-01    Laptop  Electronics   55000  2026      1    1   Thursday
1 2026-01-02     Mouse  Electronics    2100  2026      1    2     Friday
2 2026-01-03     Chair    Furniture   10000  2026      1    3   Saturday
3 2026-01-04   Monitor  Electronics   30000  2026      1    4     Sunday
4 2026-01-05     Table    Furniture   16000  2026      1    5     Monday
5 2026-01-06    Laptop  Electronics  110000  2026      1    6    Tuesday
6 2026-01-07  Keyboard  Electronics    6000  2026      1    7  Wednesday
7 2026-01-08      Sofa    Furniture   35000  2026      1    8   Thursday
8 2026-01-09   Monitor  Electronics   15000  2026      1    9     Friday

In [20]:
df.sort_values("Date")

         Date   Product     Category   Sales  Year  Month  Day    DayName
0  2026-01-01    Laptop  Electronics   55000  2026      1    1   Thursday
1  2026-01-02     Mouse  Electronics    2100  2026      1    2     Friday
2  2026-01-03     Chair    Furniture   10000  2026      1    3   Saturday
3  2026-01-04   Monitor  Electronics   30000  2026      1    4     Sunday
4  2026-01-05     Table    Furniture   16000  2026      1    5     Monday
5  2026-01-06    Laptop  Electronics  110000  2026      1    6    Tuesday
6  2026-01-07  Keyboard  Electronics    6000  2026      1    7  Wednesday
7  2026-01-08      Sofa    Furniture   35000  2026      1    8   Thursday
8  2026-01-09   Monitor  Electronics   15000  2026      1    9     Friday
9  2026-01-10     Chair    Furniture   12500  2026      1   10   Saturday
10 2026-01-11    Laptop  Electronics   55000  2026      1   11     Sunday
11 2026-01-12     Mouse  Electronics    1400  2026      1   12     Monday
12 2026-01-13     Table    Furniture    8000  2026      1   13    Tuesday
13 2026-01-14   Monitor  Electronics   15000  2026      1   14  Wednesday
14 2026-01-15      Sofa    Furniture   35000  2026      1   15   Thursday

In [21]:
df.sort_values("Date", ascending=False)

         Date   Product     Category   Sales  Year  Month  Day    DayName
14 2026-01-15      Sofa    Furniture   35000  2026      1   15   Thursday
13 2026-01-14   Monitor  Electronics   15000  2026      1   14  Wednesday
12 2026-01-13     Table    Furniture    8000  2026      1   13    Tuesday
11 2026-01-12     Mouse  Electronics    1400  2026      1   12     Monday
10 2026-01-11    Laptop  Electronics   55000  2026      1   11     Sunday
9  2026-01-10     Chair    Furniture   12500  2026      1   10   Saturday
8  2026-01-09   Monitor  Electronics   15000  2026      1    9     Friday
7  2026-01-08      Sofa    Furniture   35000  2026      1    8   Thursday
6  2026-01-07  Keyboard  Electronics    6000  2026      1    7  Wednesday
5  2026-01-06    Laptop  Electronics  110000  2026      1    6    Tuesday
4  2026-01-05     Table    Furniture   16000  2026      1    5     Monday
3  2026-01-04   Monitor  Electronics   30000  2026      1    4     Sunday
2  2026-01-03     Chair    Furniture   10000  2026      1    3   Saturday
1  2026-01-02     Mouse  Electronics    2100  2026      1    2     Friday
0  2026-01-01    Laptop  Electronics   55000  2026      1    1   Thursday

In [24]:
df.to_csv(
    "output/daily_sales_processed.csv",
    index=False
)

In [23]:
df = df.set_index("Date")

In [25]:
df.head()

            Product     Category  Sales  Year  Month  Day   DayName
Date
2026-01-01   Laptop  Electronics  55000  2026      1    1  Thursday
2026-01-02    Mouse  Electronics   2100  2026      1    2    Friday
2026-01-03    Chair    Furniture  10000  2026      1    3  Saturday
2026-01-04  Monitor  Electronics  30000  2026      1    4    Sunday
2026-01-05    Table    Furniture  16000  2026      1    5    Monday

In [26]:
df["Sales"].resample("W").sum()

Date
2026-01-04     97100
2026-01-11    249500
2026-01-18     59400
Freq: W-SUN, Name: Sales, dtype: int64

In [28]:
df["Sales"].resample("ME").sum()

Date
2026-01-31    406000
Freq: ME, Name: Sales, dtype: int64

In [29]:
df["Sales"].resample("D").mean()

Date
2026-01-01     55000.0
2026-01-02      2100.0
2026-01-03     10000.0
2026-01-04     30000.0
2026-01-05     16000.0
2026-01-06    110000.0
2026-01-07      6000.0
2026-01-08     35000.0
2026-01-09     15000.0
2026-01-10     12500.0
2026-01-11     55000.0
2026-01-12      1400.0
2026-01-13      8000.0
2026-01-14     15000.0
2026-01-15     35000.0
Freq: D, Name: Sales, dtype: float64

In [30]:
df["Sales"].rolling(3).mean()

Date
2026-01-01             NaN
2026-01-02             NaN
2026-01-03    22366.666667
2026-01-04    14033.333333
2026-01-05    18666.666667
2026-01-06    52000.000000
2026-01-07    44000.000000
2026-01-08    50333.333333
2026-01-09    18666.666667
2026-01-10    20833.333333
2026-01-11    27500.000000
2026-01-12    22966.666667
2026-01-13    21466.666667
2026-01-14     8133.333333
2026-01-15    19333.333333
Name: Sales, dtype: float64

In [31]:
df["Sales"].cumsum()

Date
2026-01-01     55000
2026-01-02     57100
2026-01-03     67100
2026-01-04     97100
2026-01-05    113100
2026-01-06    223100
2026-01-07    229100
2026-01-08    264100
2026-01-09    279100
2026-01-10    291600
2026-01-11    346600
2026-01-12    348000
2026-01-13    356000
2026-01-14    371000
2026-01-15    406000
Name: Sales, dtype: int64

In [32]:
df["Sales"].diff()

Date
2026-01-01         NaN
2026-01-02    -52900.0
2026-01-03      7900.0
2026-01-04     20000.0
2026-01-05    -14000.0
2026-01-06     94000.0
2026-01-07   -104000.0
2026-01-08     29000.0
2026-01-09    -20000.0
2026-01-10     -2500.0
2026-01-11     42500.0
2026-01-12    -53600.0
2026-01-13      6600.0
2026-01-14      7000.0
2026-01-15     20000.0
Name: Sales, dtype: float64

In [33]:
df["MovingAverage"] = df["Sales"].rolling(3).mean()

df["CumulativeSales"] = df["Sales"].cumsum()

df["DailyChange"] = df["Sales"].diff()

In [34]:
df.head()

,Product,Category,Sales,Year,Month,Day,DayName,MovingAverage,CumulativeSales,DailyChange
Date,,,,,,,,,,
2026-01-01,Laptop,Electronics,55000,2026,1,1,Thursday,NaN,55000,NaN
2026-01-02,Mouse,Electronics,2100,2026,1,2,Friday,NaN,57100,-52900.0
2026-01-03,Chair,Furniture,10000,2026,1,3,Saturday,22366.666667,67100,7900.0
2026-01-04,Monitor,Electronics,30000,2026,1,4,Sunday,14033.333333,97100,20000.0
2026-01-05,Table,Furniture,16000,2026,1,5,Monday,18666.666667,113100,-14000.0

In [35]:
df.to_csv(
    "output/time_series_dashboard.csv"
)

In [38]:
df.loc["2026-01-05"]

Product                   Table
Category              Furniture
Sales                     16000
Year                       2026
Month                         1
Day                           5
DayName                  Monday
MovingAverage      18666.666667
CumulativeSales          113100
DailyChange            -14000.0
Name: 2026-01-05 00:00:00, dtype: object

In [37]:
df.loc["2026-01-05":"2026-01-10"]

,Product,Category,Sales,Year,Month,Day,DayName,MovingAverage,CumulativeSales,DailyChange
Date,,,,,,,,,,
2026-01-05,Table,Furniture,16000,2026,1,5,Monday,18666.666667,113100,-14000.0
2026-01-06,Laptop,Electronics,110000,2026,1,6,Tuesday,52000.000000,223100,94000.0
2026-01-07,Keyboard,Electronics,6000,2026,1,7,Wednesday,44000.000000,229100,-104000.0
2026-01-08,Sofa,Furniture,35000,2026,1,8,Thursday,50333.333333,264100,29000.0
2026-01-09,Monitor,Electronics,15000,2026,1,9,Friday,18666.666667,279100,-20000.0
2026-01-10,Chair,Furniture,12500,2026,1,10,Saturday,20833.333333,291600,-2500.0

In [39]:
df["YesterdaySales"] = df["Sales"].shift(1)

In [40]:
df["SalesDifference"] = (
    df["Sales"] -
    df["YesterdaySales"]
)

In [41]:
df["GrowthRate"] = df["Sales"].pct_change()

In [42]:
df["GrowthRate"] = (
    df["Sales"]
    .pct_change()
    * 100
)

In [43]:
df["Sales"].idxmax()

Timestamp('2026-01-06 00:00:00')

In [44]:
df["Sales"].max()

np.int64(110000)

In [45]:
df["Sales"].idxmin()

Timestamp('2026-01-12 00:00:00')

In [46]:
df["Sales"].min()

np.int64(1400)

In [47]:
df["MovingAverage"] = df["Sales"].rolling(3).mean()

df["CumulativeSales"] = df["Sales"].cumsum()

df["YesterdaySales"] = df["Sales"].shift(1)

df["SalesDifference"] = (
    df["Sales"] -
    df["YesterdaySales"]
)

df["GrowthRate"] = (
    df["Sales"].pct_change()
    * 100
)

In [48]:
total_sales = df["Sales"].sum()

In [49]:
total_sales = df["Sales"].mean()

In [50]:
total_sales = df["Sales"].max()

In [51]:
total_sales = df["Sales"].min()

In [52]:
df.to_csv(
    "output/sales_trend_dashboard.csv"
)