In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/home/sanjay/Project/Project100/Pandas-learning-projects/Data-cleaning/data/employees_dirty.csv")

In [3]:
df.head()

   EmployeeID     Name Department   Age Salary  Experience        City
0         101   Alice          IT  25.0  50000         2.0     Chennai
1         102      Bob         HR  29.0    NaN         5.0  Coimbatore
2         103  Charlie         IT   NaN  65000         4.0   Bangalore
3         104    David    Finance  35.0  72000         8.0         NaN
4         105      Eva         HR  28.0  58000         3.0  Coimbatore

In [4]:
df.head(10)

   EmployeeID     Name Department   Age Salary  Experience        City
0         101   Alice          IT  25.0  50000         2.0     Chennai
1         102      Bob         HR  29.0    NaN         5.0  Coimbatore
2         103  Charlie         IT   NaN  65000         4.0   Bangalore
3         104    David    Finance  35.0  72000         8.0         NaN
4         105      Eva         HR  28.0  58000         3.0  Coimbatore
5         106    Frank         IT  31.0  61000         6.0     Chennai
6         106    Frank         IT  31.0  61000         6.0     Chennai
7         107    Grace    finance  27.0  59000         4.0   Bangalore
8         108    Henry         HR  26.0    abc         2.0     Madurai
9         109      Ivy        IT   30.0  67000         NaN     Chennai

In [5]:
df.tail()

    EmployeeID   Name Department   Age Salary  Experience        City
6          106  Frank         IT  31.0  61000         6.0     Chennai
7          107  Grace    finance  27.0  59000         4.0   Bangalore
8          108  Henry         HR  26.0    abc         2.0     Madurai
9          109    Ivy        IT   30.0  67000         NaN     Chennai
10         110   Jack         HR  29.0  60000         5.0  Coimbatore

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  11 non-null     int64
 1   Name        11 non-null     str
 2   Department  11 non-null     str
 3   Age         10 non-null     float64
 4   Salary      10 non-null     str
 5   Experience  10 non-null     float64
 6   City        10 non-null     str
dtypes: float64(2), int64(1), str(4)
memory usage: 748.0 bytes

In [7]:
df.isnull()

    EmployeeID   Name  Department    Age  Salary  Experience   City
0        False  False       False  False   False       False  False
1        False  False       False  False    True       False  False
2        False  False       False   True   False       False  False
3        False  False       False  False   False       False   True
4        False  False       False  False   False       False  False
5        False  False       False  False   False       False  False
6        False  False       False  False   False       False  False
7        False  False       False  False   False       False  False
8        False  False       False  False   False       False  False
9        False  False       False  False   False        True  False
10       False  False       False  False   False       False  False

In [8]:
df.isnull().sum()

EmployeeID    0
Name          0
Department    0
Age           1
Salary        1
Experience    1
City          1
dtype: int64

In [9]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
dtype: bool

In [10]:
df.duplicated().sum()

np.int64(1)

In [11]:
df = df.drop_duplicates()

In [12]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.isnull().sum()

EmployeeID    0
Name          0
Department    0
Age           1
Salary        1
Experience    1
City          1
dtype: int64

In [17]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [18]:
df["Salary"].dtype

In [19]:
df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")

In [20]:
df.isnull().sum()

EmployeeID    0
Name          0
Department    0
Age           0
Salary        2
Experience    1
City          1
dtype: int64

In [21]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

In [22]:
df["Experience"] = df["Experience"].fillna(df["Experience"].median())

In [23]:
df["City"] = df["City"].fillna(df["City"].mode()[0])

In [24]:
df["Name"] = df["Name"].str.strip()

df["Department"] = df["Department"].str.strip()

df["City"] = df["City"].str.strip()

In [25]:
df["Department"] = df["Department"].str.title()

In [26]:
df["Name"] = df["Name"].str.title()

In [27]:
df["Department"].unique()

<StringArray>
['It', 'Hr', 'Finance']
Length: 3, dtype: str

In [28]:
df["Department"].value_counts()

Department
It         4
Hr         4
Finance    2
Name: count, dtype: int64

In [29]:
df.dtypes

EmployeeID      int64
Name              str
Department        str
Age           float64
Salary        float64
Experience    float64
City              str
dtype: object

In [30]:
df.isnull().sum()

EmployeeID    0
Name          0
Department    0
Age           0
Salary        0
Experience    0
City          0
dtype: int64

In [32]:
df.to_csv("output/cleaned_employees.csv", index=False)