In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("data/customer_reviews.csv")

In [4]:
df.head()

   CustomerID CustomerName        City              Email               Review
0         101       alice      chennai    ALICE@gmail.com   Excellent Product
1         102          BOB  Coimbatore      bob@GMAIL.COM    Very Good Service
2         103      charlie   bangalore  Charlie@yahoo.com    average delivery
3         104        David     Chennai    david@gmail.com       GOOD Packaging
4         105          EVA     Madurai      eva@gmail.com       late Delivery

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    8 non-null      int64
 1   CustomerName  8 non-null      str
 2   City          8 non-null      str
 3   Email         8 non-null      str
 4   Review        8 non-null      str
dtypes: int64(1), str(4)
memory usage: 452.0 bytes

In [6]:
df["CustomerName"] = df["CustomerName"].str.strip()

df["Review"] = df["Review"].str.strip()

In [7]:
df["City"] = df["City"].str.upper()

In [8]:
df["Email"] = df["Email"].str.lower()

In [9]:
df["CustomerName"] = df["CustomerName"].str.title()

In [10]:
df["ReviewLength"] = df["Review"].str.len()

In [11]:
df.to_csv(
    "output/reviews_cleaned.csv",
    index=False
)

In [13]:
df[df["Review"].str.contains("Excellent")]

,CustomerID,CustomerName,City,Email,Review,ReviewLength
0,101,Alice,CHENNAI,alice@gmail.com,Excellent Product,17
5,106,Frank,COIMBATORE,frank@yahoo.com,Excellent Product,17
7,108,Henry,CHENNAI,henry@gmail.com,Excellent PRODUCT,17

In [14]:
df[df["Review"].str.contains("excellent", case=False)]

,CustomerID,CustomerName,City,Email,Review,ReviewLength
0,101,Alice,CHENNAI,alice@gmail.com,Excellent Product,17
5,106,Frank,COIMBATORE,frank@yahoo.com,Excellent Product,17
7,108,Henry,CHENNAI,henry@gmail.com,Excellent PRODUCT,17

In [15]:
df[
    df["Review"].str.contains(
        "excellent|good",
        case=False
    )
]

,CustomerID,CustomerName,City,Email,Review,ReviewLength
0,101,Alice,CHENNAI,alice@gmail.com,Excellent Product,17
1,102,Bob,COIMBATORE,bob@gmail.com,Very Good Service,17
3,104,David,CHENNAI,david@gmail.com,GOOD Packaging,14
5,106,Frank,COIMBATORE,frank@yahoo.com,Excellent Product,17
6,107,Grace,BANGALORE,grace@gmail.com,Good packaging,14
7,108,Henry,CHENNAI,henry@gmail.com,Excellent PRODUCT,17

In [16]:
df[df["CustomerName"].str.startswith("A")]

,CustomerID,CustomerName,City,Email,Review,ReviewLength
0,101,Alice,CHENNAI,alice@gmail.com,Excellent Product,17

In [17]:
df[
    df["CustomerName"].str.lower().str.startswith("a")
]

,CustomerID,CustomerName,City,Email,Review,ReviewLength
0,101,Alice,CHENNAI,alice@gmail.com,Excellent Product,17

In [18]:
df[df["Email"].str.endswith("@gmail.com")]

,CustomerID,CustomerName,City,Email,Review,ReviewLength
0,101,Alice,CHENNAI,alice@gmail.com,Excellent Product,17
1,102,Bob,COIMBATORE,bob@gmail.com,Very Good Service,17
3,104,David,CHENNAI,david@gmail.com,GOOD Packaging,14
4,105,Eva,MADURAI,eva@gmail.com,late Delivery,13
6,107,Grace,BANGALORE,grace@gmail.com,Good packaging,14
7,108,Henry,CHENNAI,henry@gmail.com,Excellent PRODUCT,17

In [19]:
df["Review"] = df["Review"].str.replace(
    "Good",
    "Positive",
    case=False
)

In [21]:
df["Review"]

0        Excellent Product
1    Very Positive Service
2         average delivery
3       Positive Packaging
4            late Delivery
5        Excellent Product
6       Positive packaging
7        Excellent PRODUCT
Name: Review, dtype: str

In [22]:
df["Email"].str.split("@")

0      [alice, gmail.com]
1        [bob, gmail.com]
2    [charlie, yahoo.com]
3      [david, gmail.com]
4        [eva, gmail.com]
5      [frank, yahoo.com]
6      [grace, gmail.com]
7      [henry, gmail.com]
Name: Email, dtype: object

In [23]:
df["Email"].str.split("@").str[0]

0      alice
1        bob
2    charlie
3      david
4        eva
5      frank
6      grace
7      henry
Name: Email, dtype: object

In [24]:
df["EmailUsername"] = df["Email"].str.split("@").str[0]

In [25]:
df["EmailDomain"] = df["Email"].str.split("@").str[1]

In [26]:
df["Domain"] = df["Email"].str.extract(
    r"@(.+)"
)

In [27]:
df["OrderCode"] = [
    "ORD-1001",
    "ORD-1002",
    "ORD-1003",
    "ORD-1004",
    "ORD-1005",
    "ORD-1006",
    "ORD-1007",
    "ORD-1008"
]

In [28]:
df["OrderNumber"] = df["OrderCode"].str.extract(
    r"(\d+)"
)

In [29]:
df["Review"].str.contains(
    "excellent",
    case=False
).sum()

np.int64(3)

In [30]:
def categorize_review(review):

    review = review.lower()

    if "excellent" in review:
        return "Excellent"

    elif "good" in review:
        return "Good"

    elif "average" in review:
        return "Average"

    elif "late" in review:
        return "Negative"

    else:
        return "Other"

In [31]:
df["ReviewCategory"] = df["Review"].apply(
    categorize_review
)

In [32]:
df[
    [
        "CustomerName",
        "Review",
        "ReviewCategory"
    ]
]

  CustomerName                 Review ReviewCategory
0        Alice      Excellent Product      Excellent
1          Bob  Very Positive Service          Other
2      Charlie       average delivery        Average
3        David     Positive Packaging          Other
4          Eva          late Delivery       Negative
5        Frank      Excellent Product      Excellent
6        Grace     Positive packaging          Other
7        Henry      Excellent PRODUCT      Excellent

In [33]:
df["ReviewCategory"].value_counts()

ReviewCategory
Excellent    3
Other        3
Average      1
Negative     1
Name: count, dtype: int64

In [35]:
df["Phone"] = [
    "+91 98765 43210",
    "9876543211",
    "+91-98765-43212",
    "98765 43213",
    "+91 98765-43214",
    "9876543215",
    "+91-98765-43216",
    "98765 43217"
]

In [36]:
df["Phone"] = df["Phone"].str.replace(" ", "", regex=False)

In [37]:
df["Phone"] = df["Phone"].str.replace("+91", "", regex=False)

In [38]:
df["Phone"] = df["Phone"].str.replace("-", "", regex=False)

In [39]:
df["Phone"]

0    9876543210
1    9876543211
2    9876543212
3    9876543213
4    9876543214
5    9876543215
6    9876543216
7    9876543217
Name: Phone, dtype: str

In [40]:
df["ValidPhone"] = df["Phone"].str.match(r"^\d{10}$")

In [41]:
df["ValidEmail"] = df["Email"].str.match(
    r"^[\w\.-]+@[\w\.-]+\.\w+$"
)

In [42]:
df[["Email", "ValidEmail"]]

               Email  ValidEmail
0    alice@gmail.com        True
1      bob@gmail.com        True
2  charlie@yahoo.com        True
3    david@gmail.com        True
4      eva@gmail.com        True
5    frank@yahoo.com        True
6    grace@gmail.com        True
7    henry@gmail.com        True

In [44]:
df["WordCount"] = df["Review"].str.split().str.len()

In [45]:
df["CharacterCount"] = df["Review"].str.len()

In [46]:
negative_keywords = [
    "late",
    "bad",
    "poor",
    "damaged"
]

In [47]:
pattern = "|".join(negative_keywords)

In [48]:
pattern

'late|bad|poor|damaged'

In [49]:
df["HasNegativeKeyword"] = df["Review"].str.contains(
    pattern,
    case=False,
    na=False
)

In [50]:
positive_keywords = [
    "excellent",
    "good",
    "great"
]

In [51]:
positive_pattern = "|".join(positive_keywords)

In [52]:
df["HasPositiveKeyword"] = df["Review"].str.contains(
    positive_pattern,
    case=False,
    na=False
)

In [53]:
df["HasPositiveKeyword"].sum()

np.int64(3)

In [54]:
df["HasNegativeKeyword"].sum()

np.int64(1)

In [55]:
def classify_sentiment(row):

    if row["HasPositiveKeyword"] and not row["HasNegativeKeyword"]:
        return "Positive"

    elif row["HasNegativeKeyword"] and not row["HasPositiveKeyword"]:
        return "Negative"

    elif row["HasPositiveKeyword"] and row["HasNegativeKeyword"]:
        return "Mixed"

    else:
        return "Neutral"

In [56]:
df["Sentiment"] = df.apply(
    classify_sentiment,
    axis=1
)

In [58]:
df["Sentiment"].value_counts()

Sentiment
Neutral     4
Positive    3
Negative    1
Name: count, dtype: int64

In [59]:
df.groupby("City")["Sentiment"].value_counts()

City        Sentiment
BANGALORE   Neutral      2
CHENNAI     Positive     2
            Neutral      1
COIMBATORE  Neutral      1
            Positive     1
MADURAI     Negative     1
Name: count, dtype: int64

In [60]:
final_report = df[
    [
        "CustomerID",
        "CustomerName",
        "City",
        "Email",
        "Review",
        "ReviewLength",
        "WordCount",
        "EmailDomain",
        "ValidEmail",
        "ValidPhone",
        "Sentiment"
    ]
]

In [61]:
final_report

,CustomerID,CustomerName,City,Email,Review,ReviewLength,WordCount,EmailDomain,ValidEmail,ValidPhone,Sentiment
0,101,Alice,CHENNAI,alice@gmail.com,Excellent Product,17,2,gmail.com,True,True,Positive
1,102,Bob,COIMBATORE,bob@gmail.com,Very Positive Service,17,3,gmail.com,True,True,Neutral
2,103,Charlie,BANGALORE,charlie@yahoo.com,average delivery,16,2,yahoo.com,True,True,Neutral
3,104,David,CHENNAI,david@gmail.com,Positive Packaging,14,2,gmail.com,True,True,Neutral
4,105,Eva,MADURAI,eva@gmail.com,late Delivery,13,2,gmail.com,True,True,Negative
5,106,Frank,COIMBATORE,frank@yahoo.com,Excellent Product,17,2,yahoo.com,True,True,Positive
6,107,Grace,BANGALORE,grace@gmail.com,Positive packaging,14,2,gmail.com,True,True,Neutral
7,108,Henry,CHENNAI,henry@gmail.com,Excellent PRODUCT,17,2,gmail.com,True,True,Positive

In [62]:
final_report.to_csv(
    "output/customer_review_report.csv",
    index=False
)