In [1]:
import pandas as pd

In [2]:
customers = pd.read_csv(
    "data/olist_customers_dataset.csv"
)

geolocation = pd.read_csv(
    "data/olist_geolocation_dataset.csv"
)

order_items = pd.read_csv(
    "data/olist_order_items_dataset.csv"
)

order_payments = pd.read_csv(
    "data/olist_order_payments_dataset.csv"
)

order_reviews = pd.read_csv(
    "data/olist_order_reviews_dataset.csv"
)

orders = pd.read_csv(
    "data/olist_orders_dataset.csv"
)

products = pd.read_csv(
    "data/olist_products_dataset.csv"
)

sellers = pd.read_csv(
    "data/olist_sellers_dataset.csv"
)

category_translation = pd.read_csv(
    "data/product_category_name_translation.csv"
)

In [3]:
print(customers.shape)
print("-------------------------------------------------------------------------------------------------------------------------")
print(customers.info())
print("-------------------------------------------------------------------------------------------------------------------------")
print(customers.head())
print("-------------------------------------------------------------------------------------------------------------------------")
print(customers.tail())
print("-------------------------------------------------------------------------------------------------------------------------")
print(customers.columns)
print("-------------------------------------------------------------------------------------------------------------------------")
print(customers.describe())
print("-------------------------------------------------------------------------------------------------------------------------")
print(customers.isnull())
print("-------------------------------------------------------------------------------------------------------------------------")
print(customers.isnull().sum())
print("-------------------------------------------------------------------------------------------------------------------------")
print(customers.duplicated())
print("-------------------------------------------------------------------------------------------------------------------------")
print(customers.duplicated().sum())
print("-------------------------------------------------------------------------------------------------------------------------")
print(customers.dtypes)

(99441, 5)
-------------------------------------------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB
None
-------------------------------------------------------------------------------------------------------------------------
                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
2                      1151              sao paulo             SP
3                      8775        mogi das cruzes             SP
4                     13056               campinas             SP
-------------------------------------------------------------------------------------------------------------------------
                            customer_id                customer_unique_id  \
99436  17ddf5dd5d51696bb3d7c6291687be6f  1a29b476fee25c95fbafc67c5ac95cf8
99437  e7b71a9017aa05c9a7fd292d714858e8  d52a67c98be1cf6a5c84435bd38d095d
99438  5e28dfe12db7fb50a4b2f691faecea5e  e9f50caf99f032f0bf3c55141f019d99
99439  56b18e2166679b8a959d72dd06da27f9  73c2643a0a458b49f58cea58833b192e
99440  274fa6071e5e17fe303b9748641082c8  84732c5050c01db9b23e19ba39899398

       customer_zip_code_prefix    customer_city customer_state
99436                      3937        sao paulo             SP
99437                      6764  taboao da serra             SP
99438                     60115        fortaleza             CE
99439                     92120           canoas             RS
99440                      6703            cotia             SP
-------------------------------------------------------------------------------------------------------------------------
Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')
-------------------------------------------------------------------------------------------------------------------------
       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000
-------------------------------------------------------------------------------------------------------------------------
       customer_id  customer_unique_id  customer_zip_code_prefix  \
0            False               False                     False
1            False               False                     False
2            False               False                     False
3            False               False                     False
4            False               False                     False
...            ...                 ...                       ...
99436        False               False                     False
99437        False               False                     False
99438        False               False                     False
99439        False               False                     False
99440        False               False                     False

       customer_city  customer_state
0              False           False
1              False           False
2              False           False
3              False           False
4              False           False
...              ...             ...
99436          False           False
99437          False           False
99438          False           False
99439          False           False
99440          False           False

[99441 rows x 5 columns]
-------------------------------------------------------------------------------------------------------------------------
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64
-------------------------------------------------------------------------------------------------------------------------
0        False
1        False
2        False
3        False
4        False
         ...
99436    False
99437    False
99438    False
99439    False
99440    False
Length: 99441, dtype: bool
-------------------------------------------------------------------------------------------------------------------------
0
-------------------------------------------------------------------------------------------------------------------------
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

In [4]:
print(geolocation.shape)
print("-------------------------------------------------------------------------------------------------------------------------")
print(geolocation.info())
print("-------------------------------------------------------------------------------------------------------------------------")
print(geolocation.head())
print("-------------------------------------------------------------------------------------------------------------------------")
print(geolocation.tail())
print("-------------------------------------------------------------------------------------------------------------------------")
print(geolocation.columns)
print("-------------------------------------------------------------------------------------------------------------------------")
print(geolocation.describe())
print("-------------------------------------------------------------------------------------------------------------------------")
print(geolocation.isnull())
print("-------------------------------------------------------------------------------------------------------------------------")
print(geolocation.isnull().sum())
print("-------------------------------------------------------------------------------------------------------------------------")
print(geolocation.duplicated())
print("-------------------------------------------------------------------------------------------------------------------------")
print(geolocation.duplicated().sum())
print("-------------------------------------------------------------------------------------------------------------------------")
print(geolocation.dtypes)

(1000163, 5)
-------------------------------------------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 38.2 MB
None
-------------------------------------------------------------------------------------------------------------------------
   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                         1037       -23.545621       -46.639292
1                         1046       -23.546081       -46.644820
2                         1046       -23.546129       -46.642951
3                         1041       -23.544392       -46.639499
4                         1035       -23.541578       -46.641607

  geolocation_city geolocation_state
0        sao paulo                SP
1        sao paulo                SP
2        sao paulo                SP
3        sao paulo                SP
4        sao paulo                SP
-------------------------------------------------------------------------------------------------------------------------
         geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
1000158                        99950       -28.068639       -52.010705
1000159                        99900       -27.877125       -52.224882
1000160                        99950       -28.071855       -52.014716
1000161                        99980       -28.388932       -51.846871
1000162                        99950       -28.070104       -52.018658

        geolocation_city geolocation_state
1000158         tapejara                RS
1000159   getulio vargas                RS
1000160         tapejara                RS
1000161  david canabarro                RS
1000162         tapejara                RS
-------------------------------------------------------------------------------------------------------------------------
Index(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng',
       'geolocation_city', 'geolocation_state'],
      dtype='str')
-------------------------------------------------------------------------------------------------------------------------
       geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
count                 1.000163e+06     1.000163e+06     1.000163e+06
mean                  3.657417e+04    -2.117615e+01    -4.639054e+01
std                   3.054934e+04     5.715866e+00     4.269748e+00
min                   1.001000e+03    -3.660537e+01    -1.014668e+02
25%                   1.107500e+04    -2.360355e+01    -4.857317e+01
50%                   2.653000e+04    -2.291938e+01    -4.663788e+01
75%                   6.350400e+04    -1.997962e+01    -4.376771e+01
max                   9.999000e+04     4.506593e+01     1.211054e+02
-------------------------------------------------------------------------------------------------------------------------
         geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                              False            False            False
1                              False            False            False
2                              False            False            False
3                              False            False            False
4                              False            False            False
...                              ...              ...              ...
1000158                        False            False            False
1000159                        False            False            False
1000160                        False            False            False
1000161                        False            False            False
1000162                        False            False            False

         geolocation_city  geolocation_state
0                   False              False
1                   False              False
2                   False              False
3                   False              False
4                   False              False
...                   ...                ...
1000158             False              False
1000159             False              False
1000160             False              False
1000161             False              False
1000162             False              False

[1000163 rows x 5 columns]
-------------------------------------------------------------------------------------------------------------------------
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64
-------------------------------------------------------------------------------------------------------------------------
0          False
1          False
2          False
3          False
4          False
           ...
1000158    False
1000159     True
1000160     True
1000161    False
1000162     True
Length: 1000163, dtype: bool
-------------------------------------------------------------------------------------------------------------------------
261831
-------------------------------------------------------------------------------------------------------------------------
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

In [5]:
print(order_items.shape)
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_items.info())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_items.head())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_items.tail())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_items.columns)
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_items.describe())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_items.isnull())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_items.isnull().sum())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_items.duplicated())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_items.duplicated().sum())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_items.dtypes)

(112650, 7)
-------------------------------------------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB
None
-------------------------------------------------------------------------------------------------------------------------
                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1
2  000229ec398224ef6ca0657da4fc703e              1
3  00024acbcdf0a6daa1e931b038114c75              1
4  00042b26cf59d7ce69dfabb4e55b4fd9              1

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87

   shipping_limit_date   price  freight_value
0  2017-09-19 09:45:35   58.90          13.29
1  2017-05-03 11:05:13  239.90          19.93
2  2018-01-18 14:48:30  199.00          17.87
3  2018-08-15 10:10:18   12.99          12.79
4  2017-02-13 13:57:51  199.90          18.14
-------------------------------------------------------------------------------------------------------------------------
                                order_id  order_item_id  \
112645  fffc94f6ce00a00581880bf54a75a037              1
112646  fffcd46ef2263f404302a634eb57f7eb              1
112647  fffce4705a9662cd70adb13d4a31832d              1
112648  fffe18544ffabc95dfada21779c9644f              1
112649  fffe41c64501cc87c801fd61db3f6244              1

                              product_id                         seller_id  \
112645  4aa6014eceb682077f9dc4bffebc05b0  b8bc237ba3788b23da09c0f1f3a3288c
112646  32e07fd915822b0765e448c4dd74c828  f3c38ab652836d21de61fb8314b69182
112647  72a30483855e2eafc67aee5dc2560482  c3cfdc648177fdbbbb35635a37472c53
112648  9c422a519119dcad7575db5af1ba540e  2b3e4a2a3ea8e01938cabda2a3e5cc79
112649  350688d9dc1e75ff97be326363655e01  f7ccf836d21b2fb1de37564105216cc1

        shipping_limit_date   price  freight_value
112645  2018-05-02 04:11:01  299.99          43.41
112646  2018-07-20 04:31:48  350.00          36.53
112647  2017-10-30 17:14:25   99.90          16.95
112648  2017-08-21 00:04:32   55.99           8.72
112649  2018-06-12 17:10:13   43.00          12.79
-------------------------------------------------------------------------------------------------------------------------
Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='str')
-------------------------------------------------------------------------------------------------------------------------
       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000
-------------------------------------------------------------------------------------------------------------------------
        order_id  order_item_id  product_id  seller_id  shipping_limit_date  \
0          False          False       False      False                False
1          False          False       False      False                False
2          False          False       False      False                False
3          False          False       False      False                False
4          False          False       False      False                False
...          ...            ...         ...        ...                  ...
112645     False          False       False      False                False
112646     False          False       False      False                False
112647     False          False       False      False                False
112648     False          False       False      False                False
112649     False          False       False      False                False

        price  freight_value
0       False          False
1       False          False
2       False          False
3       False          False
4       False          False
...       ...            ...
112645  False          False
112646  False          False
112647  False          False
112648  False          False
112649  False          False

[112650 rows x 7 columns]
-------------------------------------------------------------------------------------------------------------------------
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64
-------------------------------------------------------------------------------------------------------------------------
0         False
1         False
2         False
3         False
4         False
          ...
112645    False
112646    False
112647    False
112648    False
112649    False
Length: 112650, dtype: bool
-------------------------------------------------------------------------------------------------------------------------
0
-------------------------------------------------------------------------------------------------------------------------
order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

In [6]:
print(order_payments.shape)
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_payments.info())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_payments.head())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_payments.tail())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_payments.columns)
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_payments.describe())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_payments.isnull())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_payments.isnull().sum())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_payments.duplicated())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_payments.duplicated().sum())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_payments.dtypes)

(103886, 5)
-------------------------------------------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB
None
-------------------------------------------------------------------------------------------------------------------------
                           order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card

   payment_installments  payment_value
0                     8          99.33
1                     1          24.39
2                     1          65.71
3                     8         107.78
4                     2         128.45
-------------------------------------------------------------------------------------------------------------------------
                                order_id  payment_sequential payment_type  \
103881  0406037ad97740d563a178ecc7a2075c                   1       boleto
103882  7b905861d7c825891d6347454ea7863f                   1  credit_card
103883  32609bbb3dd69b3c066a6860554a77bf                   1  credit_card
103884  b8b61059626efa996a60be9bb9320e10                   1  credit_card
103885  28bbae6599b09d39ca406b747b6632b1                   1       boleto

        payment_installments  payment_value
103881                     1         363.31
103882                     2          96.80
103883                     1          47.77
103884                     5         369.54
103885                     1         191.58
-------------------------------------------------------------------------------------------------------------------------
Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='str')
-------------------------------------------------------------------------------------------------------------------------
       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000
-------------------------------------------------------------------------------------------------------------------------
        order_id  payment_sequential  payment_type  payment_installments  \
0          False               False         False                 False
1          False               False         False                 False
2          False               False         False                 False
3          False               False         False                 False
4          False               False         False                 False
...          ...                 ...           ...                   ...
103881     False               False         False                 False
103882     False               False         False                 False
103883     False               False         False                 False
103884     False               False         False                 False
103885     False               False         False                 False

        payment_value
0               False
1               False
2               False
3               False
4               False
...               ...
103881          False
103882          False
103883          False
103884          False
103885          False

[103886 rows x 5 columns]
-------------------------------------------------------------------------------------------------------------------------
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64
-------------------------------------------------------------------------------------------------------------------------
0         False
1         False
2         False
3         False
4         False
          ...
103881    False
103882    False
103883    False
103884    False
103885    False
Length: 103886, dtype: bool
-------------------------------------------------------------------------------------------------------------------------
0
-------------------------------------------------------------------------------------------------------------------------
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

In [7]:
print(order_reviews.shape)
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_reviews.info())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_reviews.head())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_reviews.tail())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_reviews.columns)
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_reviews.describe())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_reviews.isnull())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_reviews.isnull().sum())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_reviews.duplicated())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_reviews.duplicated().sum())
print("-------------------------------------------------------------------------------------------------------------------------")
print(order_reviews.dtypes)

(99224, 7)
-------------------------------------------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB
None
-------------------------------------------------------------------------------------------------------------------------
                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1

   review_score review_comment_title  \
0             4                  NaN
1             5                  NaN
2             5                  NaN
3             5                  NaN
4             5                  NaN

                              review_comment_message review_creation_date  \
0                                                NaN  2018-01-18 00:00:00
1                                                NaN  2018-03-10 00:00:00
2                                                NaN  2018-02-17 00:00:00
3              Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00
4  Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00

  review_answer_timestamp
0     2018-01-18 21:46:59
1     2018-03-11 03:05:13
2     2018-02-18 14:36:24
3     2017-04-21 22:02:06
4     2018-03-02 10:26:53
-------------------------------------------------------------------------------------------------------------------------
                              review_id                          order_id  \
99219  574ed12dd733e5fa530cfd4bbf39d7c9  2a8c23fee101d4d5662fa670396eb8da
99220  f3897127253a9592a73be9bdfdf4ed7a  22ec9f0669f784db00fa86d035cf8602
99221  b3de70c89b1510c4cd3d0649fd302472  55d4004744368f5571d1f590031933e4
99222  1adeb9d84d72fe4e337617733eb85149  7725825d039fc1f0ceb7635e3f7d9206
99223  efe49f1d6f951dd88b51e6ccd4cc548f  90531360ecb1eec2a1fbb265a0db0508

       review_score review_comment_title  \
99219             5                  NaN
99220             5                  NaN
99221             5                  NaN
99222             4                  NaN
99223             1                  NaN

                                  review_comment_message review_creation_date  \
99219                                                NaN  2018-07-07 00:00:00
99220                                                NaN  2017-12-09 00:00:00
99221  Excelente mochila, entrega super rápida. Super...  2018-03-22 00:00:00
99222                                                NaN  2018-07-01 00:00:00
99223  meu produto chegou e ja tenho que devolver, po...  2017-07-03 00:00:00

      review_answer_timestamp
99219     2018-07-14 17:18:30
99220     2017-12-11 20:06:42
99221     2018-03-23 09:10:43
99222     2018-07-02 12:59:13
99223     2017-07-03 21:01:49
-------------------------------------------------------------------------------------------------------------------------
Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='str')
-------------------------------------------------------------------------------------------------------------------------
       review_score
count  99224.000000
mean       4.086421
std        1.347579
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000
-------------------------------------------------------------------------------------------------------------------------
       review_id  order_id  review_score  review_comment_title  \
0          False     False         False                  True
1          False     False         False                  True
2          False     False         False                  True
3          False     False         False                  True
4          False     False         False                  True
...          ...       ...           ...                   ...
99219      False     False         False                  True
99220      False     False         False                  True
99221      False     False         False                  True
99222      False     False         False                  True
99223      False     False         False                  True

       review_comment_message  review_creation_date  review_answer_timestamp
0                        True                 False                    False
1                        True                 False                    False
2                        True                 False                    False
3                       False                 False                    False
4                       False                 False                    False
...                       ...                   ...                      ...
99219                    True                 False                    False
99220                    True                 False                    False
99221                   False                 False                    False
99222                    True                 False                    False
99223                   False                 False                    False

[99224 rows x 7 columns]
-------------------------------------------------------------------------------------------------------------------------
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64
-------------------------------------------------------------------------------------------------------------------------
0        False
1        False
2        False
3        False
4        False
         ...
99219    False
99220    False
99221    False
99222    False
99223    False
Length: 99224, dtype: bool
-------------------------------------------------------------------------------------------------------------------------
0
-------------------------------------------------------------------------------------------------------------------------
review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

In [8]:
print(orders.shape)
print("-------------------------------------------------------------------------------------------------------------------------")
print(orders.info())
print("-------------------------------------------------------------------------------------------------------------------------")
print(orders.head())
print("-------------------------------------------------------------------------------------------------------------------------")
print(orders.tail())
print("-------------------------------------------------------------------------------------------------------------------------")
print(orders.columns)
print("-------------------------------------------------------------------------------------------------------------------------")
print(orders.describe())
print("-------------------------------------------------------------------------------------------------------------------------")
print(orders.isnull())
print("-------------------------------------------------------------------------------------------------------------------------")
print(orders.isnull().sum())
print("-------------------------------------------------------------------------------------------------------------------------")
print(orders.duplicated())
print("-------------------------------------------------------------------------------------------------------------------------")
print(orders.duplicated().sum())
print("-------------------------------------------------------------------------------------------------------------------------")
print(orders.dtypes)

(99441, 8)
-------------------------------------------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB
None
-------------------------------------------------------------------------------------------------------------------------
                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date
0           2017-10-18 00:00:00
1           2018-08-13 00:00:00
2           2018-09-04 00:00:00
3           2017-12-15 00:00:00
4           2018-02-26 00:00:00
-------------------------------------------------------------------------------------------------------------------------
                               order_id                       customer_id  \
99436  9c5dedf39a927c1b2549525ed64a053c  39bd1228ee8140590ac3aca26f2dfe00
99437  63943bddc261676b46f01ca7ac2f7bd8  1fca14ff2861355f6e5f14306ff977a7
99438  83c1379a015df1e13d02aae0204711ab  1aa71eb042121263aafbe80c1b562c9c
99439  11c177c8e97725db2631073c19f07b62  b331b74b18dc79bcdf6532d51e1637c1
99440  66dea50a8b16d9b4dee7af250b4be1a5  edb027a75a1449115f6b43211ae02a24

      order_status order_purchase_timestamp    order_approved_at  \
99436    delivered      2017-03-09 09:54:05  2017-03-09 09:54:05
99437    delivered      2018-02-06 12:58:58  2018-02-06 13:10:37
99438    delivered      2017-08-27 14:46:43  2017-08-27 15:04:16
99439    delivered      2018-01-08 21:28:27  2018-01-08 21:36:21
99440    delivered      2018-03-08 20:57:30  2018-03-09 11:20:28

      order_delivered_carrier_date order_delivered_customer_date  \
99436          2017-03-10 11:18:03           2017-03-17 15:08:01
99437          2018-02-07 23:22:42           2018-02-28 17:37:56
99438          2017-08-28 20:52:26           2017-09-21 11:24:17
99439          2018-01-12 15:35:03           2018-01-25 23:32:54
99440          2018-03-09 22:11:59           2018-03-16 13:08:30

      order_estimated_delivery_date
99436           2017-03-28 00:00:00
99437           2018-03-02 00:00:00
99438           2017-09-27 00:00:00
99439           2018-02-15 00:00:00
99440           2018-04-03 00:00:00
-------------------------------------------------------------------------------------------------------------------------
Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')
-------------------------------------------------------------------------------------------------------------------------
                                order_id                       customer_id  \
count                              99441                             99441
unique                             99441                             99441
top     e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
freq                                   1                                 1

       order_status order_purchase_timestamp    order_approved_at  \
count         99441                    99441                99281
unique            8                    98875                90733
top       delivered      2018-03-31 15:08:21  2018-02-27 04:31:10
freq          96478                        3                    9

       order_delivered_carrier_date order_delivered_customer_date  \
count                         97658                         96476
unique                        81018                         95664
top             2018-05-09 15:48:00           2018-05-14 20:02:44
freq                             47                             3

       order_estimated_delivery_date
count                          99441
unique                           459
top              2017-12-20 00:00:00
freq                             522
-------------------------------------------------------------------------------------------------------------------------
       order_id  customer_id  order_status  order_purchase_timestamp  \
0         False        False         False                     False
1         False        False         False                     False
2         False        False         False                     False
3         False        False         False                     False
4         False        False         False                     False
...         ...          ...           ...                       ...
99436     False        False         False                     False
99437     False        False         False                     False
99438     False        False         False                     False
99439     False        False         False                     False
99440     False        False         False                     False

       order_approved_at  order_delivered_carrier_date  \
0                  False                         False
1                  False                         False
2                  False                         False
3                  False                         False
4                  False                         False
...                  ...                           ...
99436              False                         False
99437              False                         False
99438              False                         False
99439              False                         False
99440              False                         False

       order_delivered_customer_date  order_estimated_delivery_date
0                              False                          False
1                              False                          False
2                              False                          False
3                              False                          False
4                              False                          False
...                              ...                            ...
99436                          False                          False
99437                          False                          False
99438                          False                          False
99439                          False                          False
99440                          False                          False

[99441 rows x 8 columns]
-------------------------------------------------------------------------------------------------------------------------
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
-------------------------------------------------------------------------------------------------------------------------
0        False
1        False
2        False
3        False
4        False
         ...
99436    False
99437    False
99438    False
99439    False
99440    False
Length: 99441, dtype: bool
-------------------------------------------------------------------------------------------------------------------------
0
-------------------------------------------------------------------------------------------------------------------------
order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

In [9]:
print(products.shape)
print("-------------------------------------------------------------------------------------------------------------------------")
print(products.info())
print("-------------------------------------------------------------------------------------------------------------------------")
print(products.head())
print("-------------------------------------------------------------------------------------------------------------------------")
print(products.tail())
print("-------------------------------------------------------------------------------------------------------------------------")
print(products.columns)
print("-------------------------------------------------------------------------------------------------------------------------")
print(products.describe())
print("-------------------------------------------------------------------------------------------------------------------------")
print(products.isnull())
print("-------------------------------------------------------------------------------------------------------------------------")
print(products.isnull().sum())
print("-------------------------------------------------------------------------------------------------------------------------")
print(products.duplicated())
print("-------------------------------------------------------------------------------------------------------------------------")
print(products.duplicated().sum())
print("-------------------------------------------------------------------------------------------------------------------------")
print(products.dtypes)

(32951, 9)
-------------------------------------------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB
None
-------------------------------------------------------------------------------------------------------------------------
                         product_id  product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer
3  cef67bcfe19066a932b7673e239eb23d                  bebes
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0
1                 44.0                       276.0                 1.0
2                 46.0                       250.0                 1.0
3                 27.0                       261.0                 1.0
4                 37.0                       402.0                 4.0

   product_weight_g  product_length_cm  product_height_cm  product_width_cm
0             225.0               16.0               10.0              14.0
1            1000.0               30.0               18.0              20.0
2             154.0               18.0                9.0              15.0
3             371.0               26.0                4.0              26.0
4             625.0               20.0               17.0              13.0
-------------------------------------------------------------------------------------------------------------------------
                             product_id              product_category_name  \
32946  a0b7d5a992ccda646f2d34e418fff5a0                   moveis_decoracao
32947  bf4538d88321d0fd4412a93c974510e6  construcao_ferramentas_iluminacao
32948  9a7c6041fa9592d9d9ef6cfe62a71f8c                    cama_mesa_banho
32949  83808703fc0706a22e264b9d75f04a2e             informatica_acessorios
32950  106392145fca363410d287a815be6de4                    cama_mesa_banho

       product_name_lenght  product_description_lenght  product_photos_qty  \
32946                 45.0                        67.0                 2.0
32947                 41.0                       971.0                 1.0
32948                 50.0                       799.0                 1.0
32949                 60.0                       156.0                 2.0
32950                 58.0                       309.0                 1.0

       product_weight_g  product_length_cm  product_height_cm  \
32946           12300.0               40.0               40.0
32947            1700.0               16.0               19.0
32948            1400.0               27.0                7.0
32949             700.0               31.0               13.0
32950            2083.0               12.0                2.0

       product_width_cm
32946              40.0
32947              16.0
32948              27.0
32949              20.0
32950               7.0
-------------------------------------------------------------------------------------------------------------------------
Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='str')
-------------------------------------------------------------------------------------------------------------------------
       product_name_lenght  product_description_lenght  product_photos_qty  \
count         32341.000000                32341.000000        32341.000000
mean             48.476949                  771.495285            2.188986
std              10.245741                  635.115225            1.736766
min               5.000000                    4.000000            1.000000
25%              42.000000                  339.000000            1.000000
50%              51.000000                  595.000000            1.000000
75%              57.000000                  972.000000            3.000000
max              76.000000                 3992.000000           20.000000

       product_weight_g  product_length_cm  product_height_cm  \
count      32949.000000       32949.000000       32949.000000
mean        2276.472488          30.815078          16.937661
std         4282.038731          16.914458          13.637554
min            0.000000           7.000000           2.000000
25%          300.000000          18.000000           8.000000
50%          700.000000          25.000000          13.000000
75%         1900.000000          38.000000          21.000000
max        40425.000000         105.000000         105.000000

       product_width_cm
count      32949.000000
mean          23.196728
std           12.079047
min            6.000000
25%           15.000000
50%           20.000000
75%           30.000000
max          118.000000
-------------------------------------------------------------------------------------------------------------------------
       product_id  product_category_name  product_name_lenght  \
0           False                  False                False
1           False                  False                False
2           False                  False                False
3           False                  False                False
4           False                  False                False
...           ...                    ...                  ...
32946       False                  False                False
32947       False                  False                False
32948       False                  False                False
32949       False                  False                False
32950       False                  False                False

       product_description_lenght  product_photos_qty  product_weight_g  \
0                           False               False             False
1                           False               False             False
2                           False               False             False
3                           False               False             False
4                           False               False             False
...                           ...                 ...               ...
32946                       False               False             False
32947                       False               False             False
32948                       False               False             False
32949                       False               False             False
32950                       False               False             False

       product_length_cm  product_height_cm  product_width_cm
0                  False              False             False
1                  False              False             False
2                  False              False             False
3                  False              False             False
4                  False              False             False
...                  ...                ...               ...
32946              False              False             False
32947              False              False             False
32948              False              False             False
32949              False              False             False
32950              False              False             False

[32951 rows x 9 columns]
-------------------------------------------------------------------------------------------------------------------------
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64
-------------------------------------------------------------------------------------------------------------------------
0        False
1        False
2        False
3        False
4        False
         ...
32946    False
32947    False
32948    False
32949    False
32950    False
Length: 32951, dtype: bool
-------------------------------------------------------------------------------------------------------------------------
0
-------------------------------------------------------------------------------------------------------------------------
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [10]:
print(sellers.shape)
print("-------------------------------------------------------------------------------------------------------------------------")
print(sellers.info())
print("-------------------------------------------------------------------------------------------------------------------------")
print(sellers.head())
print("-------------------------------------------------------------------------------------------------------------------------")
print(sellers.tail())
print("-------------------------------------------------------------------------------------------------------------------------")
print(sellers.columns)
print("-------------------------------------------------------------------------------------------------------------------------")
print(sellers.describe())
print("-------------------------------------------------------------------------------------------------------------------------")
print(sellers.isnull())
print("-------------------------------------------------------------------------------------------------------------------------")
print(sellers.isnull().sum())
print("-------------------------------------------------------------------------------------------------------------------------")
print(sellers.duplicated())
print("-------------------------------------------------------------------------------------------------------------------------")
print(sellers.duplicated().sum())
print("-------------------------------------------------------------------------------------------------------------------------")
print(sellers.dtypes)

(3095, 4)
-------------------------------------------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB
None
-------------------------------------------------------------------------------------------------------------------------
                          seller_id  seller_zip_code_prefix  \
0  3442f8959a84dea7ee197c632cb2df15                   13023
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914

         seller_city seller_state
0           campinas           SP
1         mogi guacu           SP
2     rio de janeiro           RJ
3          sao paulo           SP
4  braganca paulista           SP
-------------------------------------------------------------------------------------------------------------------------
                             seller_id  seller_zip_code_prefix seller_city  \
3090  98dddbc4601dd4443ca174359b237166                   87111     sarandi
3091  f8201cab383e484733266d1906e2fdfa                   88137     palhoca
3092  74871d19219c7d518d0090283e03c137                    4650   sao paulo
3093  e603cf3fec55f8697c9059638d6c8eb5                   96080     pelotas
3094  9e25199f6ef7e7c347120ff175652c3b                   12051     taubate

     seller_state
3090           PR
3091           SC
3092           SP
3093           RS
3094           SP
-------------------------------------------------------------------------------------------------------------------------
Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='str')
-------------------------------------------------------------------------------------------------------------------------
       seller_zip_code_prefix
count             3095.000000
mean             32291.059451
std              32713.453830
min               1001.000000
25%               7093.500000
50%              14940.000000
75%              64552.500000
max              99730.000000
-------------------------------------------------------------------------------------------------------------------------
      seller_id  seller_zip_code_prefix  seller_city  seller_state
0         False                   False        False         False
1         False                   False        False         False
2         False                   False        False         False
3         False                   False        False         False
4         False                   False        False         False
...         ...                     ...          ...           ...
3090      False                   False        False         False
3091      False                   False        False         False
3092      False                   False        False         False
3093      False                   False        False         False
3094      False                   False        False         False

[3095 rows x 4 columns]
-------------------------------------------------------------------------------------------------------------------------
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64
-------------------------------------------------------------------------------------------------------------------------
0       False
1       False
2       False
3       False
4       False
        ...
3090    False
3091    False
3092    False
3093    False
3094    False
Length: 3095, dtype: bool
-------------------------------------------------------------------------------------------------------------------------
0
-------------------------------------------------------------------------------------------------------------------------
seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

In [11]:
print(category_translation.shape)
print("-------------------------------------------------------------------------------------------------------------------------")
print(category_translation.info())
print("-------------------------------------------------------------------------------------------------------------------------")
print(category_translation.head())
print("-------------------------------------------------------------------------------------------------------------------------")
print(category_translation.tail())
print("-------------------------------------------------------------------------------------------------------------------------")
print(category_translation.columns)
print("-------------------------------------------------------------------------------------------------------------------------")
print(category_translation.describe())
print("-------------------------------------------------------------------------------------------------------------------------")
print(category_translation.isnull())
print("-------------------------------------------------------------------------------------------------------------------------")
print(category_translation.isnull().sum())
print("-------------------------------------------------------------------------------------------------------------------------")
print(category_translation.duplicated())
print("-------------------------------------------------------------------------------------------------------------------------")
print(category_translation.duplicated().sum())
print("-------------------------------------------------------------------------------------------------------------------------")
print(category_translation.dtypes)

(71, 2)
-------------------------------------------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB
None
-------------------------------------------------------------------------------------------------------------------------
    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor
-------------------------------------------------------------------------------------------------------------------------
            product_category_name product_category_name_english
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services
-------------------------------------------------------------------------------------------------------------------------
Index(['product_category_name', 'product_category_name_english'], dtype='str')
-------------------------------------------------------------------------------------------------------------------------
       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1
-------------------------------------------------------------------------------------------------------------------------
    product_category_name  product_category_name_english
0                   False                          False
1                   False                          False
2                   False                          False
3                   False                          False
4                   False                          False
..                    ...                            ...
66                  False                          False
67                  False                          False
68                  False                          False
69                  False                          False
70                  False                          False

[71 rows x 2 columns]
-------------------------------------------------------------------------------------------------------------------------
product_category_name            0
product_category_name_english    0
dtype: int64
-------------------------------------------------------------------------------------------------------------------------
0     False
1     False
2     False
3     False
4     False
      ...
66    False
67    False
68    False
69    False
70    False
Length: 71, dtype: bool
-------------------------------------------------------------------------------------------------------------------------
0
-------------------------------------------------------------------------------------------------------------------------
product_category_name            str
product_category_name_english    str
dtype: object

In [12]:
print(customers.shape[0],geolocation.shape[0],order_items.shape[0],order_payments.shape[0],orders.shape[0],order_reviews.shape[0],products.shape[0],sellers.shape[0],category_translation.shape[0])
max(customers.shape[0],geolocation.shape[0],order_items.shape[0],order_payments.shape[0],orders.shape[0],order_reviews.shape[0],products.shape[0],sellers.shape[0],category_translation.shape[0])

99441 1000163 112650 103886 99441 99224 32951 3095 71

1000163

In [13]:
print(customers.shape[1],geolocation.shape[1],order_items.shape[1],order_payments.shape[1],orders.shape[1],order_reviews.shape[1],products.shape[1],sellers.shape[1],category_translation.shape[1])
max(customers.shape[1],geolocation.shape[1],order_items.shape[1],order_payments.shape[1],orders.shape[1],order_reviews.shape[1],products.shape[1],sellers.shape[1],category_translation.shape[1])

5 5 7 5 8 7 9 4 2

9

In [14]:
print(customers.isnull().sum(),geolocation.isnull().sum(),order_items.isnull().sum(),order_payments.isnull().sum(),orders.isnull().sum(),order_reviews.isnull().sum(),products.isnull().sum(),sellers.isnull().sum(),category_translation.isnull().sum())

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64 geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64 order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64 order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64 order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64 review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64 product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64 seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64 product_category_name            0
product_category_name_english    0
dtype: int64

In [15]:
print(customers.duplicated().sum(),geolocation.duplicated().sum(),order_items.duplicated().sum(),order_payments.duplicated().sum(),orders.duplicated().sum(),order_reviews.duplicated().sum(),products.duplicated().sum(),sellers.duplicated().sum(),category_translation.duplicated().sum())

0 261831 0 0 0 0 0 0 0

In [16]:
print(customers.head())
print(customers.dtypes)

                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
2                      1151              sao paulo             SP
3                      8775        mogi das cruzes             SP
4                     13056               campinas             SP
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

In [17]:
print(geolocation.head())
print(geolocation.dtypes)

   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                         1037       -23.545621       -46.639292
1                         1046       -23.546081       -46.644820
2                         1046       -23.546129       -46.642951
3                         1041       -23.544392       -46.639499
4                         1035       -23.541578       -46.641607

  geolocation_city geolocation_state
0        sao paulo                SP
1        sao paulo                SP
2        sao paulo                SP
3        sao paulo                SP
4        sao paulo                SP
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

In [18]:
print(order_items.head())
print(order_items.dtypes)

                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1
2  000229ec398224ef6ca0657da4fc703e              1
3  00024acbcdf0a6daa1e931b038114c75              1
4  00042b26cf59d7ce69dfabb4e55b4fd9              1

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87

   shipping_limit_date   price  freight_value
0  2017-09-19 09:45:35   58.90          13.29
1  2017-05-03 11:05:13  239.90          19.93
2  2018-01-18 14:48:30  199.00          17.87
3  2018-08-15 10:10:18   12.99          12.79
4  2017-02-13 13:57:51  199.90          18.14
order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

In [19]:
print(order_payments.head())
print(order_payments.dtypes)

                           order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card

   payment_installments  payment_value
0                     8          99.33
1                     1          24.39
2                     1          65.71
3                     8         107.78
4                     2         128.45
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

In [20]:
print(orders.head())
print(orders.dtypes)

                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date
0           2017-10-18 00:00:00
1           2018-08-13 00:00:00
2           2018-09-04 00:00:00
3           2017-12-15 00:00:00
4           2018-02-26 00:00:00
order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

In [21]:
print(order_reviews.head())
print(order_reviews.dtypes)

                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1

   review_score review_comment_title  \
0             4                  NaN
1             5                  NaN
2             5                  NaN
3             5                  NaN
4             5                  NaN

                              review_comment_message review_creation_date  \
0                                                NaN  2018-01-18 00:00:00
1                                                NaN  2018-03-10 00:00:00
2                                                NaN  2018-02-17 00:00:00
3              Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00
4  Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00

  review_answer_timestamp
0     2018-01-18 21:46:59
1     2018-03-11 03:05:13
2     2018-02-18 14:36:24
3     2017-04-21 22:02:06
4     2018-03-02 10:26:53
review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

In [22]:
print(products.head())
print(products.dtypes)

                         product_id  product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer
3  cef67bcfe19066a932b7673e239eb23d                  bebes
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0
1                 44.0                       276.0                 1.0
2                 46.0                       250.0                 1.0
3                 27.0                       261.0                 1.0
4                 37.0                       402.0                 4.0

   product_weight_g  product_length_cm  product_height_cm  product_width_cm
0             225.0               16.0               10.0              14.0
1            1000.0               30.0               18.0              20.0
2             154.0               18.0                9.0              15.0
3             371.0               26.0                4.0              26.0
4             625.0               20.0               17.0              13.0
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [23]:
print(sellers.head())
print(sellers.dtypes)

                          seller_id  seller_zip_code_prefix  \
0  3442f8959a84dea7ee197c632cb2df15                   13023
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914

         seller_city seller_state
0           campinas           SP
1         mogi guacu           SP
2     rio de janeiro           RJ
3          sao paulo           SP
4  braganca paulista           SP
seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

In [24]:
print(category_translation.head())
print(category_translation.dtypes)

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor
product_category_name            str
product_category_name_english    str
dtype: object

In [25]:
def missing_report(name,var):
    print(name," : ",var.isna().sum())

In [26]:
missing_report("customers",customers)

customers  :  customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [27]:
missing_report("geolocation",geolocation)

geolocation  :  geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [28]:
missing_report("order_items",order_items)

order_items  :  order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [29]:
missing_report("order_payments",order_payments)

order_payments  :  order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [30]:
missing_report("order_reviews",order_reviews)

order_reviews  :  review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [31]:
missing_report("orders",orders)

orders  :  order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [32]:
missing_report("products",products)

products  :  product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [33]:
missing_report("sellers",sellers)

sellers  :  seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [34]:
missing_report("category_translation",category_translation)

category_translation  :  product_category_name            0
product_category_name_english    0
dtype: int64

In [35]:
def duplicated_analysis(name,var):
    print(name," : ",var.duplicated().sum())

In [36]:
duplicated_analysis("customers",customers)

customers  :  0

In [37]:
duplicated_analysis("geolocation",geolocation)

geolocation  :  261831

In [38]:
duplicated_analysis("order_items",order_items)

order_items  :  0

In [39]:
duplicated_analysis("order_payments",order_payments)

order_payments  :  0

In [40]:
duplicated_analysis("order_reviews",order_reviews)

order_reviews  :  0

In [41]:
duplicated_analysis("orders",orders)

orders  :  0

In [42]:
duplicated_analysis("products",products)

products  :  0

In [43]:
duplicated_analysis("sellers",sellers)

sellers  :  0

In [44]:
duplicated_analysis("category_translation",category_translation)

category_translation  :  0

In [45]:
order_items["shipping_limit_date"] = pd.to_datetime(
    order_items["shipping_limit_date"]
)

orders["order_purchase_timestamp"] = pd.to_datetime(
    orders["order_purchase_timestamp"]
)

orders["order_approved_at"] = pd.to_datetime(
    orders["order_approved_at"]
)

orders["order_delivered_carrier_date"] = pd.to_datetime(
    orders["order_delivered_carrier_date"]
)

orders["order_delivered_customer_date"] = pd.to_datetime(
    orders["order_delivered_customer_date"]
)

orders["order_estimated_delivery_date"] = pd.to_datetime(
    orders["order_estimated_delivery_date"]
)

order_reviews["review_creation_date"] = pd.to_datetime(
    order_reviews["review_creation_date"]
)

order_reviews["review_answer_timestamp"] = pd.to_datetime(
    order_reviews["review_answer_timestamp"]
)

In [46]:
order_items.dtypes

order_id                          str
order_item_id                   int64
product_id                        str
seller_id                         str
shipping_limit_date    datetime64[us]
price                         float64
freight_value                 float64
dtype: object

In [47]:
orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [48]:
order_reviews.dtypes

review_id                             str
order_id                              str
review_score                        int64
review_comment_title                  str
review_comment_message                str
review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

In [49]:
print(order_items["shipping_limit_date"].isna())

print(order_items["shipping_limit_date"].isna().sum())

0         False
1         False
2         False
3         False
4         False
          ...
112645    False
112646    False
112647    False
112648    False
112649    False
Name: shipping_limit_date, Length: 112650, dtype: bool
0

In [50]:
print(orders["order_purchase_timestamp"].isna())

print(orders["order_purchase_timestamp"].isna().sum())

0        False
1        False
2        False
3        False
4        False
         ...
99436    False
99437    False
99438    False
99439    False
99440    False
Name: order_purchase_timestamp, Length: 99441, dtype: bool
0

In [51]:
print(orders["order_purchase_timestamp"].isna())

print(orders["order_purchase_timestamp"].isna().sum())

0        False
1        False
2        False
3        False
4        False
         ...
99436    False
99437    False
99438    False
99439    False
99440    False
Name: order_purchase_timestamp, Length: 99441, dtype: bool
0

In [52]:
print(orders["order_approved_at"].isna())

print(orders["order_approved_at"].isna().sum())

0        False
1        False
2        False
3        False
4        False
         ...
99436    False
99437    False
99438    False
99439    False
99440    False
Name: order_approved_at, Length: 99441, dtype: bool
160

In [53]:
print(orders["order_delivered_carrier_date"].isna())

print(orders["order_delivered_carrier_date"].isna().sum())

0        False
1        False
2        False
3        False
4        False
         ...
99436    False
99437    False
99438    False
99439    False
99440    False
Name: order_delivered_carrier_date, Length: 99441, dtype: bool
1783

In [54]:
print(orders["order_delivered_customer_date"].isna())

print(orders["order_delivered_customer_date"].isna().sum())

0        False
1        False
2        False
3        False
4        False
         ...
99436    False
99437    False
99438    False
99439    False
99440    False
Name: order_delivered_customer_date, Length: 99441, dtype: bool
2965

In [55]:
print(orders["order_estimated_delivery_date"].isna())

print(orders["order_estimated_delivery_date"].isna().sum())

0        False
1        False
2        False
3        False
4        False
         ...
99436    False
99437    False
99438    False
99439    False
99440    False
Name: order_estimated_delivery_date, Length: 99441, dtype: bool
0

In [56]:

print(order_reviews["review_creation_date"].isna())

print(order_reviews["review_creation_date"].isna().sum())

0        False
1        False
2        False
3        False
4        False
         ...
99219    False
99220    False
99221    False
99222    False
99223    False
Name: review_creation_date, Length: 99224, dtype: bool
0

In [57]:

print(order_reviews["review_answer_timestamp"].isna())

print(order_reviews["review_answer_timestamp"].isna().sum())

0        False
1        False
2        False
3        False
4        False
         ...
99219    False
99220    False
99221    False
99222    False
99223    False
Name: review_answer_timestamp, Length: 99224, dtype: bool
0

In [58]:
print(order_items["shipping_limit_date"].duplicated().sum())

print(orders["order_purchase_timestamp"].duplicated().sum())

print(orders["order_approved_at"].duplicated().sum())

print(orders["order_delivered_carrier_date"].duplicated().sum())

print(orders["order_delivered_customer_date"].duplicated().sum())

print(orders["order_estimated_delivery_date"].duplicated().sum())

print(order_reviews["review_creation_date"].duplicated().sum())

print(order_reviews["review_answer_timestamp"].duplicated().sum())

19332
566
8707
18422
3776
98982
98588
976

In [59]:
print(order_items["shipping_limit_date"].nunique())

print(orders["order_purchase_timestamp"].nunique())

print(orders["order_approved_at"].nunique())

print(orders["order_delivered_carrier_date"].nunique())

print(orders["order_delivered_customer_date"].nunique())

print(orders["order_estimated_delivery_date"].nunique())

print(order_reviews["review_creation_date"].nunique())

print(order_reviews["review_answer_timestamp"].nunique())

93318
98875
90733
81018
95664
459
636
98248

In [60]:
## Key Integrity Analysis

In [61]:
customers["customer_id"].nunique()
len(customers)

99441

In [62]:
orders["order_id"].nunique()
len(orders)

99441

In [63]:
orders["customer_id"].nunique()
len(orders)

99441

In [64]:
products["product_id"].nunique()
len(products)

32951

In [65]:
sellers["seller_id"].nunique()
len(sellers)

3095

In [66]:
order_items["order_id"].nunique()
len(order_items)

112650

In [67]:
order_items["product_id"].nunique()
len(order_items)

112650

In [68]:
order_items["seller_id"].nunique()
len(order_items)

112650

In [69]:
order_items.dtypes

order_id                          str
order_item_id                   int64
product_id                        str
seller_id                         str
shipping_limit_date    datetime64[us]
price                         float64
freight_value                 float64
dtype: object

In [70]:
order_payments.dtypes

order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

In [71]:
products.dtypes

product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [72]:
order_reviews.isna().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [73]:
print(customers.isna().sum())
print(customers.isna().mean()*100)

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64
customer_id                 0.0
customer_unique_id          0.0
customer_zip_code_prefix    0.0
customer_city               0.0
customer_state              0.0
dtype: float64

In [74]:
print(geolocation.isna().sum())
print(geolocation.isna().mean()*100)

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64
geolocation_zip_code_prefix    0.0
geolocation_lat                0.0
geolocation_lng                0.0
geolocation_city               0.0
geolocation_state              0.0
dtype: float64

In [75]:
print(order_items.isna().sum())
print(order_items.isna().mean()*100)

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64
order_id               0.0
order_item_id          0.0
product_id             0.0
seller_id              0.0
shipping_limit_date    0.0
price                  0.0
freight_value          0.0
dtype: float64

In [76]:
print(order_payments.isna().sum())
print(order_payments.isna().mean()*100)

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64
order_id                0.0
payment_sequential      0.0
payment_type            0.0
payment_installments    0.0
payment_value           0.0
dtype: float64

In [77]:
print(order_reviews.isna().sum())
print(order_reviews.isna().mean()*100)

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64
review_id                   0.000000
order_id                    0.000000
review_score                0.000000
review_comment_title       88.341530
review_comment_message     58.702532
review_creation_date        0.000000
review_answer_timestamp     0.000000
dtype: float64

In [78]:
print(orders.isna().sum())
print(orders.isna().mean()*100)

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
order_id                         0.000000
customer_id                      0.000000
order_status                     0.000000
order_purchase_timestamp         0.000000
order_approved_at                0.160899
order_delivered_carrier_date     1.793023
order_delivered_customer_date    2.981668
order_estimated_delivery_date    0.000000
dtype: float64

In [79]:
print(products.isna().sum())
print(products.isna().mean()*100)

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64
product_id                    0.000000
product_category_name         1.851234
product_name_lenght           1.851234
product_description_lenght    1.851234
product_photos_qty            1.851234
product_weight_g              0.006070
product_length_cm             0.006070
product_height_cm             0.006070
product_width_cm              0.006070
dtype: float64

In [80]:
print(sellers.isna().sum())
print(sellers.isna().mean()*100)

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64
seller_id                 0.0
seller_zip_code_prefix    0.0
seller_city               0.0
seller_state              0.0
dtype: float64

In [81]:
print(category_translation.isna().sum())
print(category_translation.isna().mean()*100)

product_category_name            0
product_category_name_english    0
dtype: int64
product_category_name            0.0
product_category_name_english    0.0
dtype: float64

In [82]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [83]:
orders["order_status"].value_counts(normalize=True) * 100

order_status
delivered      97.020344
shipped         1.113223
canceled        0.628513
unavailable     0.612423
invoiced        0.315765
processing      0.302692
created         0.005028
approved        0.002011
Name: proportion, dtype: float64

In [84]:
order_payments["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [85]:
order_payments[
    ["payment_value", "payment_installments"]
].describe()

       payment_value  payment_installments
count  103886.000000         103886.000000
mean      154.100380              2.853349
std       217.494064              2.687051
min         0.000000              0.000000
25%        56.790000              1.000000
50%       100.000000              1.000000
75%       171.837500              4.000000
max     13664.080000             24.000000

In [86]:
order_payments["payment_value"].sum()

np.float64(16008872.120000001)

In [87]:
order_payments["payment_value"].mean()

np.float64(154.10038041699556)

In [88]:
products["product_id"].nunique()

32951

In [89]:
products["product_category_name"].value_counts().head(10)

product_category_name
cama_mesa_banho           3029
esporte_lazer             2867
moveis_decoracao          2657
beleza_saude              2444
utilidades_domesticas     2335
automotivo                1900
informatica_acessorios    1639
brinquedos                1411
relogios_presentes        1329
telefonia                 1134
Name: count, dtype: int64

In [90]:
order_items["revenue"] = (
    order_items["price"] +
    order_items["freight_value"]
)

In [91]:
order_items["revenue"].sum()

np.float64(15843553.24)

In [92]:
order_items["revenue"].mean()

np.float64(140.6440589436307)

In [93]:
order_items.nlargest(
    10,
    "revenue"
)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,revenue
3556,0812eb902a67711a1cb742b3cdaa65ae,1,489ae2aa008f021502940f251d4cce7f,e3b4998c7a498169dc7bce44e6bb6277,2017-02-16 20:37:36,6735.00,194.31,6929.31
112233,fefacc66af859508bf1a7934eab1e97f,1,69c590f7ffc7bf8db97190b6cb6ed62e,80ceebb4ee9b31afb6c6a916a574a1e2,2018-08-02 04:05:13,6729.00,193.21,6922.21
107841,f5136e38d1a14a4dbd87dff67da82701,1,1bdf5e6731585cf01aa8169c7028d6ad,ee27a8f15b1dded4d213a468ba4eb391,2017-06-15 02:45:17,6499.00,227.66,6726.66
74336,a96610ab360d42a2e5335a3998b4718a,1,a6492cc69376c469ab6f61d8f44de961,59417c56835dd8e2e72f91f809cd4092,2017-04-18 13:25:18,4799.00,151.34,4950.34
11249,199af31afc78c699f0dbf71fb178d4d4,1,c3ed642d592594bb648ff4a04cee2747,59417c56835dd8e2e72f91f809cd4092,2017-05-09 15:50:15,4690.00,74.34,4764.34
62086,8dbc85d1447242f3b127dda390d56e19,1,259037a6a41845e455183f89c5035f18,c72de06d72748d1a0dfb2125be43ba63,2018-06-28 12:36:36,4590.00,91.78,4681.78
29193,426a9742b533fc6fed17d1fd6d143d7e,1,a1beef8f3992dbd4cd8726796aa69c53,512d298ac2a96d1931b6bd30aa21f61d,2018-08-16 14:24:28,4399.87,113.45,4513.32
56663,80dfedb6d17bf23539beeef3c768f4d7,1,4ca7b91a31637bd24fb8e559d5e015e4,59417c56835dd8e2e72f91f809cd4092,2017-05-05 20:50:13,3999.00,195.76,4194.76
45843,68101694e5c5dc7330c91e1bbc36214f,1,6cdf8fc1d741c76586d8b6b15e9eef30,ed4acab38528488b65a9a9c603ff024a,2018-04-05 08:27:27,4099.99,75.27,4175.26
78310,b239ca7cd485940b31882363b52e6674,1,dd113cb02b2af9c8e5787e8f1f0722f6,821fb029fc6e495ca4f08a35d51e53a5,2018-08-02 08:15:14,4059.00,104.51,4163.51

In [94]:
sales = orders.merge(
    customers,
    on="customer_id",
    how="left"
)

In [95]:
sales = sales.merge(
    order_items,
    on="order_id",
    how="left"
)

In [96]:
sales = sales.merge(
    products,
    on="product_id",
    how="left"
)

In [97]:
sales = sales.merge(
    sellers,
    on="seller_id",
    how="left"
)

In [98]:
sales = sales.merge(
    category_translation,
    on="product_category_name",
    how="left"
)

In [99]:
print(sales.info())

<class 'pandas.DataFrame'>
RangeIndex: 113425 entries, 0 to 113424
Data columns (total 31 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113425 non-null  str
 1   customer_id                    113425 non-null  str
 2   order_status                   113425 non-null  str
 3   order_purchase_timestamp       113425 non-null  datetime64[us]
 4   order_approved_at              113264 non-null  datetime64[us]
 5   order_delivered_carrier_date   111457 non-null  datetime64[us]
 6   order_delivered_customer_date  110196 non-null  datetime64[us]
 7   order_estimated_delivery_date  113425 non-null  datetime64[us]
 8   customer_unique_id             113425 non-null  str
 9   customer_zip_code_prefix       113425 non-null  int64
 10  customer_city                  113425 non-null  str
 11  customer_state                 113425 non-null  str
 12  order_item_id                  112650 non-null  float64
 13  product_id                     112650 non-null  str
 14  seller_id                      112650 non-null  str
 15  shipping_limit_date            112650 non-null  datetime64[us]
 16  price                          112650 non-null  float64
 17  freight_value                  112650 non-null  float64
 18  revenue                        112650 non-null  float64
 19  product_category_name          111047 non-null  str
 20  product_name_lenght            111047 non-null  float64
 21  product_description_lenght     111047 non-null  float64
 22  product_photos_qty             111047 non-null  float64
 23  product_weight_g               112632 non-null  float64
 24  product_length_cm              112632 non-null  float64
 25  product_height_cm              112632 non-null  float64
 26  product_width_cm               112632 non-null  float64
 27  seller_zip_code_prefix         112650 non-null  float64
 28  seller_city                    112650 non-null  str
 29  seller_state                   112650 non-null  str
 30  product_category_name_english  111023 non-null  str
dtypes: datetime64[us](6), float64(12), int64(1), str(12)
memory usage: 26.8 MB
None

In [100]:
print(sales.shape)

(113425, 31)

In [101]:
print(sales.head())

                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp   order_approved_at  \
0    delivered      2017-10-02 10:56:33 2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37 2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49 2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06 2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39 2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date                customer_unique_id  \
0                    2017-10-18  7c396fd4830fd04220f754e42b4e5bff
1                    2018-08-13  af07308b275d755c9edb36a90c618231
2                    2018-09-04  3a653a41f6f9fc3d2a113cf8398680e8
3                    2017-12-15  7c142cf63193a1473d2e66489a9ae977
4                    2018-02-26  72632f0f9dd73dfee390c9b22eb56dd6

   customer_zip_code_prefix  ... product_description_lenght  \
0                      3149  ...                      268.0
1                     47813  ...                      178.0
2                     75265  ...                      232.0
3                     59296  ...                      468.0
4                      9195  ...                      316.0

  product_photos_qty  product_weight_g product_length_cm product_height_cm  \
0                4.0             500.0              19.0               8.0
1                1.0             400.0              19.0              13.0
2                1.0             420.0              24.0              19.0
3                3.0             450.0              30.0              10.0
4                4.0             250.0              51.0              15.0

  product_width_cm  seller_zip_code_prefix      seller_city  seller_state  \
0             13.0                  9350.0             maua            SP
1             19.0                 31570.0   belo horizonte            SP
2             21.0                 14840.0          guariba            SP
3             20.0                 31842.0   belo horizonte            MG
4             15.0                  8752.0  mogi das cruzes            SP

  product_category_name_english
0                    housewares
1                     perfumery
2                          auto
3                      pet_shop
4                    stationery

[5 rows x 31 columns]

In [102]:
# ============================================================
# PHASE 5 → FINAL — OLIST COMPLETE PANDAS ANALYSIS
# ============================================================

print("=" * 70)
print("PHASE 5 — BUSINESS ANALYSIS")
print("=" * 70)

# ------------------------------------------------------------
# 1. ORDER STATUS ANALYSIS
# ------------------------------------------------------------

print("\n--- Order Status Count ---")
print(orders["order_status"].value_counts())

print("\n--- Order Status Percentage ---")
print(
    (orders["order_status"].value_counts(normalize=True) * 100)
    .round(2)
)


# ------------------------------------------------------------
# 2. PAYMENT ANALYSIS
# ------------------------------------------------------------

print("\n--- Payment Types ---")
print(order_payments["payment_type"].value_counts())

print("\n--- Payment Statistics ---")
print(
    order_payments[
        ["payment_value", "payment_installments"]
    ].describe()
)

print("\nTotal Payment Value:",
      round(order_payments["payment_value"].sum(), 2))

print("Average Payment Value:",
      round(order_payments["payment_value"].mean(), 2))


# ------------------------------------------------------------
# 3. PRODUCT ANALYSIS
# ------------------------------------------------------------

print("\n--- Total Unique Products ---")
print(products["product_id"].nunique())

print("\n--- Top 10 Product Categories ---")
print(
    products["product_category_name"]
    .value_counts()
    .head(10)
)


# ------------------------------------------------------------
# 4. SALES / REVENUE CALCULATION
# ------------------------------------------------------------

order_items["revenue"] = (
    order_items["price"] +
    order_items["freight_value"]
)

print("\n--- Revenue Statistics ---")
print(
    order_items["revenue"].describe()
)

print("\nTotal Revenue:",
      round(order_items["revenue"].sum(), 2))

print("\n--- Top 10 Highest Value Items ---")
print(
    order_items.nlargest(
        10,
        "revenue"
    )
)


# ============================================================
# PHASE 6 — MERGE / CREATE MASTER DATASET
# ============================================================

print("\n" + "=" * 70)
print("PHASE 6 — MERGING DATASETS")
print("=" * 70)

# Orders + Customers
sales = orders.merge(
    customers,
    on="customer_id",
    how="left"
)

# + Order Items
sales = sales.merge(
    order_items,
    on="order_id",
    how="left"
)

# + Products
sales = sales.merge(
    products,
    on="product_id",
    how="left"
)

# + Sellers
sales = sales.merge(
    sellers,
    on="seller_id",
    how="left"
)

# + English category names
sales = sales.merge(
    category_translation,
    on="product_category_name",
    how="left"
)

print("\nMaster Dataset Shape:")
print(sales.shape)

print("\nMaster Dataset Info:")
sales.info()

print("\nMaster Dataset Preview:")
display(sales.head())


# ============================================================
# PHASE 7 — CUSTOMER ANALYSIS
# ============================================================

print("\n" + "=" * 70)
print("PHASE 7 — CUSTOMER ANALYSIS")
print("=" * 70)

print("\n--- Customers by State ---")
print(
    sales["customer_state"]
    .value_counts()
    .head(10)
)

print("\n--- Customers by City ---")
print(
    sales["customer_city"]
    .value_counts()
    .head(10)
)


# ============================================================
# PHASE 8 — CATEGORY ANALYSIS
# ============================================================

print("\n" + "=" * 70)
print("PHASE 8 — CATEGORY ANALYSIS")
print("=" * 70)

category_sales = (
    sales
    .groupby("product_category_name_english")
    .agg(
        Orders=("order_id", "nunique"),
        Items=("order_item_id", "count"),
        Revenue=("revenue", "sum")
    )
    .reset_index()
    .sort_values(
        "Revenue",
        ascending=False
    )
)

print("\n--- Top 10 Categories by Revenue ---")
display(
    category_sales.head(10)
)

print("\n--- Top 10 Categories by Orders ---")
display(
    category_sales
    .sort_values(
        "Orders",
        ascending=False
    )
    .head(10)
)


# ============================================================
# PHASE 9 — SELLER ANALYSIS
# ============================================================

print("\n" + "=" * 70)
print("PHASE 9 — SELLER ANALYSIS")
print("=" * 70)

seller_sales = (
    sales
    .groupby(
        ["seller_id", "seller_state"]
    )
    .agg(
        Orders=("order_id", "nunique"),
        Items=("order_item_id", "count"),
        Revenue=("revenue", "sum")
    )
    .reset_index()
    .sort_values(
        "Revenue",
        ascending=False
    )
)

print("\n--- Top 10 Sellers ---")
display(
    seller_sales.head(10)
)


# ============================================================
# PHASE 10 — TIME SERIES ANALYSIS
# ============================================================

print("\n" + "=" * 70)
print("PHASE 10 — TIME SERIES ANALYSIS")
print("=" * 70)

sales["order_purchase_timestamp"] = pd.to_datetime(
    sales["order_purchase_timestamp"],
    errors="coerce"
)

sales["year"] = (
    sales["order_purchase_timestamp"].dt.year
)

sales["month"] = (
    sales["order_purchase_timestamp"].dt.month
)

sales["month_name"] = (
    sales["order_purchase_timestamp"]
    .dt.month_name()
)

sales["year_month"] = (
    sales["order_purchase_timestamp"]
    .dt.to_period("M")
)

# Monthly Revenue
monthly_sales = (
    sales
    .set_index("order_purchase_timestamp")
    ["revenue"]
    .resample("ME")
    .sum()
    .reset_index()
)

monthly_sales.columns = [
    "Month",
    "Revenue"
]

print("\n--- Monthly Revenue ---")
display(monthly_sales)

# Monthly Orders
monthly_orders = (
    sales
    .set_index("order_purchase_timestamp")
    ["order_id"]
    .resample("ME")
    .nunique()
    .reset_index()
)

monthly_orders.columns = [
    "Month",
    "Orders"
]

print("\n--- Monthly Orders ---")
display(monthly_orders)

# Highest revenue month
print("\nHighest Revenue Month:")
display(
    monthly_sales.loc[
        monthly_sales["Revenue"].idxmax()
    ]
)


# ============================================================
# PHASE 11 — PIVOT TABLES
# ============================================================

print("\n" + "=" * 70)
print("PHASE 11 — PIVOT TABLES")
print("=" * 70)

state_category = pd.pivot_table(
    sales,
    values="revenue",
    index="customer_state",
    columns="product_category_name_english",
    aggfunc="sum",
    fill_value=0
)

print("\n--- State × Category Revenue Pivot ---")
display(
    state_category.head()
)

# Payment × Order Status
payment_summary = pd.crosstab(
    orders["order_status"],
    order_payments["payment_type"]
)

print("\n--- Payment Type × Order Status ---")
display(payment_summary)


# ============================================================
# PHASE 12 — STRING OPERATIONS
# ============================================================

print("\n" + "=" * 70)
print("PHASE 12 — STRING OPERATIONS")
print("=" * 70)

# Clean customer city
sales["customer_city"] = (
    sales["customer_city"]
    .astype("string")
    .str.strip()
    .str.lower()
)

# Clean category
sales["product_category_name_english"] = (
    sales["product_category_name_english"]
    .astype("string")
    .str.strip()
    .str.lower()
)

print("\n--- Categories containing 'bed' ---")

bed_categories = sales[
    sales["product_category_name_english"]
    .str.contains(
        "bed",
        na=False
    )
]

display(
    bed_categories[
        ["product_category_name_english"]
    ]
    .drop_duplicates()
    .head(20)
)


# ============================================================
# PHASE 13 — DELIVERY ANALYSIS
# ============================================================

print("\n" + "=" * 70)
print("PHASE 13 — DELIVERY ANALYSIS")
print("=" * 70)

sales["order_delivered_customer_date"] = pd.to_datetime(
    sales["order_delivered_customer_date"],
    errors="coerce"
)

sales["order_estimated_delivery_date"] = pd.to_datetime(
    sales["order_estimated_delivery_date"],
    errors="coerce"
)

sales["delivery_days"] = (
    sales["order_delivered_customer_date"]
    - sales["order_purchase_timestamp"]
).dt.days

sales["delivery_difference"] = (
    sales["order_estimated_delivery_date"]
    - sales["order_delivered_customer_date"]
).dt.days

print("\nAverage Delivery Days:")
print(
    round(
        sales["delivery_days"].mean(),
        2
    )
)

print("\nFastest Delivery:")
print(
    sales["delivery_days"].min()
)

print("\nSlowest Delivery:")
print(
    sales["delivery_days"].max()
)

print("\nDelivery Statistics:")
display(
    sales["delivery_days"].describe()
)


# ============================================================
# PHASE 14 — FINAL BUSINESS QUESTIONS
# ============================================================

print("\n" + "=" * 70)
print("PHASE 14 — FINAL BUSINESS QUESTIONS")
print("=" * 70)


# Q1 — Total Revenue
total_revenue = sales["revenue"].sum()

print("\nQ1. Total Revenue:")
print(round(total_revenue, 2))


# Q2 — Top Category
top_category = (
    category_sales
    .iloc[0]
)

print("\nQ2. Top Category by Revenue:")
print(top_category)


# Q3 — Top Seller
top_seller = seller_sales.iloc[0]

print("\nQ3. Top Seller:")
print(top_seller)


# Q4 — State with highest revenue
state_revenue = (
    sales
    .groupby("customer_state")["revenue"]
    .sum()
    .sort_values(
        ascending=False
    )
)

print("\nQ4. Top State by Revenue:")
print(state_revenue.head(10))


# Q5 — Average Order Value
order_values = (
    sales
    .groupby("order_id")["revenue"]
    .sum()
)

average_order_value = order_values.mean()

print("\nQ5. Average Order Value:")
print(round(average_order_value, 2))


# Q6 — Most common payment type
common_payment = (
    order_payments["payment_type"]
    .value_counts()
    .idxmax()
)

print("\nQ6. Most Common Payment Type:")
print(common_payment)


# Q7 — Highest payment value by payment type
payment_value_summary = (
    order_payments
    .groupby("payment_type")["payment_value"]
    .sum()
    .sort_values(
        ascending=False
    )
)

print("\nQ7. Payment Type by Total Value:")
print(payment_value_summary)


# Q8 — Highest revenue month
highest_revenue_month = (
    monthly_sales
    .loc[
        monthly_sales["Revenue"].idxmax()
    ]
)

print("\nQ8. Highest Revenue Month:")
print(highest_revenue_month)


# Q9 — Highest order month
highest_order_month = (
    monthly_orders
    .loc[
        monthly_orders["Orders"].idxmax()
    ]
)

print("\nQ9. Highest Order Month:")
print(highest_order_month)


# Q10 — Category with highest average item price
category_avg_price = (
    sales
    .groupby(
        "product_category_name_english"
    )["price"]
    .mean()
    .sort_values(
        ascending=False
    )
)

print("\nQ10. Category with Highest Average Item Price:")
print(category_avg_price.head(10))


# Q11 — State with highest average order value
state_order_value = (
    sales
    .groupby(
        ["customer_state", "order_id"]
    )["revenue"]
    .sum()
    .groupby(level=0)
    .mean()
    .sort_values(
        ascending=False
    )
)

print("\nQ11. State with Highest Average Order Value:")
print(state_order_value.head(10))


# Q12 — Delivered order percentage
total_orders = orders["order_id"].nunique()

delivered_orders = orders[
    orders["order_status"] == "delivered"
]["order_id"].nunique()

delivered_percentage = (
    delivered_orders /
    total_orders *
    100
)

print("\nQ12. Delivered Orders %:")
print(round(delivered_percentage, 2))


# Q13 — Cancelled order percentage
cancelled_orders = orders[
    orders["order_status"] == "canceled"
]["order_id"].nunique()

cancelled_percentage = (
    cancelled_orders /
    total_orders *
    100
)

print("\nQ13. Cancelled Orders %:")
print(round(cancelled_percentage, 2))


# Q14 — Average delivery time
print("\nQ14. Average Delivery Time:")
print(
    round(
        sales["delivery_days"].mean(),
        2
    )
)


# Q15 — Category with longest average delivery time
category_delivery = (
    sales
    .groupby(
        "product_category_name_english"
    )["delivery_days"]
    .mean()
    .sort_values(
        ascending=False
    )
)

print("\nQ15. Categories with Longest Average Delivery:")
print(category_delivery.head(10))


# ============================================================
# PHASE 15 — FINAL REPORT EXPORT
# ============================================================

print("\n" + "=" * 70)
print("PHASE 15 — EXPORTING FINAL REPORT")
print("=" * 70)

# CSV reports
category_sales.to_csv(
    "output/category_sales.csv",
    index=False
)

seller_sales.to_csv(
    "output/seller_sales.csv",
    index=False
)

monthly_sales.to_csv(
    "output/monthly_sales.csv",
    index=False
)

monthly_orders.to_csv(
    "output/monthly_orders.csv",
    index=False
)

state_revenue.reset_index(
    name="Revenue"
).to_csv(
    "output/state_revenue.csv",
    index=False
)

# Final Excel workbook
with pd.ExcelWriter(
    "output/olist_analysis_report.xlsx"
) as writer:

    category_sales.to_excel(
        writer,
        sheet_name="Category Sales",
        index=False
    )

    seller_sales.to_excel(
        writer,
        sheet_name="Seller Sales",
        index=False
    )

    monthly_sales.to_excel(
        writer,
        sheet_name="Monthly Revenue",
        index=False
    )

    monthly_orders.to_excel(
        writer,
        sheet_name="Monthly Orders",
        index=False
    )

    state_revenue.reset_index(
        name="Revenue"
    ).to_excel(
        writer,
        sheet_name="State Revenue",
        index=False
    )

    state_category.to_excel(
        writer,
        sheet_name="State Category"
    )

    payment_summary.to_excel(
        writer,
        sheet_name="Payment Summary"
    )

    # Keep Excel file manageable
    sales.head(10000).to_excel(
        writer,
        sheet_name="Sample Master Data",
        index=False
    )

print("\n" + "=" * 70)
print("✅ PANDAS FINAL PROJECT COMPLETED")
print("=" * 70)

print("\nGenerated files:")
print("output/category_sales.csv")
print("output/seller_sales.csv")
print("output/monthly_sales.csv")
print("output/monthly_orders.csv")
print("output/state_revenue.csv")
print("output/olist_analysis_report.xlsx")

======================================================================
PHASE 5 — BUSINESS ANALYSIS
======================================================================

--- Order Status Count ---
order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

--- Order Status Percentage ---
order_status
delivered      97.02
shipped         1.11
canceled        0.63
unavailable     0.61
invoiced        0.32
processing      0.30
created         0.01
approved        0.00
Name: proportion, dtype: float64

--- Payment Types ---
payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

--- Payment Statistics ---
       payment_value  payment_installments
count  103886.000000         103886.000000
mean      154.100380              2.853349
std       217.494064              2.687051
min         0.000000              0.000000
25%        56.790000              1.000000
50%       100.000000              1.000000
75%       171.837500              4.000000
max     13664.080000             24.000000

Total Payment Value: 16008872.12
Average Payment Value: 154.1

--- Total Unique Products ---
32951

--- Top 10 Product Categories ---
product_category_name
cama_mesa_banho           3029
esporte_lazer             2867
moveis_decoracao          2657
beleza_saude              2444
utilidades_domesticas     2335
automotivo                1900
informatica_acessorios    1639
brinquedos                1411
relogios_presentes        1329
telefonia                 1134
Name: count, dtype: int64

--- Revenue Statistics ---
count    112650.000000
mean        140.644059
std         190.724394
min           6.080000
25%          55.220000
50%          92.320000
75%         157.937500
max        6929.310000
Name: revenue, dtype: float64

Total Revenue: 15843553.24

--- Top 10 Highest Value Items ---
                                order_id  order_item_id  \
3556    0812eb902a67711a1cb742b3cdaa65ae              1
112233  fefacc66af859508bf1a7934eab1e97f              1
107841  f5136e38d1a14a4dbd87dff67da82701              1
74336   a96610ab360d42a2e5335a3998b4718a              1
11249   199af31afc78c699f0dbf71fb178d4d4              1
62086   8dbc85d1447242f3b127dda390d56e19              1
29193   426a9742b533fc6fed17d1fd6d143d7e              1
56663   80dfedb6d17bf23539beeef3c768f4d7              1
45843   68101694e5c5dc7330c91e1bbc36214f              1
78310   b239ca7cd485940b31882363b52e6674              1

                              product_id                         seller_id  \
3556    489ae2aa008f021502940f251d4cce7f  e3b4998c7a498169dc7bce44e6bb6277
112233  69c590f7ffc7bf8db97190b6cb6ed62e  80ceebb4ee9b31afb6c6a916a574a1e2
107841  1bdf5e6731585cf01aa8169c7028d6ad  ee27a8f15b1dded4d213a468ba4eb391
74336   a6492cc69376c469ab6f61d8f44de961  59417c56835dd8e2e72f91f809cd4092
11249   c3ed642d592594bb648ff4a04cee2747  59417c56835dd8e2e72f91f809cd4092
62086   259037a6a41845e455183f89c5035f18  c72de06d72748d1a0dfb2125be43ba63
29193   a1beef8f3992dbd4cd8726796aa69c53  512d298ac2a96d1931b6bd30aa21f61d
56663   4ca7b91a31637bd24fb8e559d5e015e4  59417c56835dd8e2e72f91f809cd4092
45843   6cdf8fc1d741c76586d8b6b15e9eef30  ed4acab38528488b65a9a9c603ff024a
78310   dd113cb02b2af9c8e5787e8f1f0722f6  821fb029fc6e495ca4f08a35d51e53a5

       shipping_limit_date    price  freight_value  revenue
3556   2017-02-16 20:37:36  6735.00         194.31  6929.31
112233 2018-08-02 04:05:13  6729.00         193.21  6922.21
107841 2017-06-15 02:45:17  6499.00         227.66  6726.66
74336  2017-04-18 13:25:18  4799.00         151.34  4950.34
11249  2017-05-09 15:50:15  4690.00          74.34  4764.34
62086  2018-06-28 12:36:36  4590.00          91.78  4681.78
29193  2018-08-16 14:24:28  4399.87         113.45  4513.32
56663  2017-05-05 20:50:13  3999.00         195.76  4194.76
45843  2018-04-05 08:27:27  4099.99          75.27  4175.26
78310  2018-08-02 08:15:14  4059.00         104.51  4163.51

======================================================================
PHASE 6 — MERGING DATASETS
======================================================================

Master Dataset Shape:
(113425, 31)

Master Dataset Info:
<class 'pandas.DataFrame'>
RangeIndex: 113425 entries, 0 to 113424
Data columns (total 31 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113425 non-null  str
 1   customer_id                    113425 non-null  str
 2   order_status                   113425 non-null  str
 3   order_purchase_timestamp       113425 non-null  datetime64[us]
 4   order_approved_at              113264 non-null  datetime64[us]
 5   order_delivered_carrier_date   111457 non-null  datetime64[us]
 6   order_delivered_customer_date  110196 non-null  datetime64[us]
 7   order_estimated_delivery_date  113425 non-null  datetime64[us]
 8   customer_unique_id             113425 non-null  str
 9   customer_zip_code_prefix       113425 non-null  int64
 10  customer_city                  113425 non-null  str
 11  customer_state                 113425 non-null  str
 12  order_item_id                  112650 non-null  float64
 13  product_id                     112650 non-null  str
 14  seller_id                      112650 non-null  str
 15  shipping_limit_date            112650 non-null  datetime64[us]
 16  price                          112650 non-null  float64
 17  freight_value                  112650 non-null  float64
 18  revenue                        112650 non-null  float64
 19  product_category_name          111047 non-null  str
 20  product_name_lenght            111047 non-null  float64
 21  product_description_lenght     111047 non-null  float64
 22  product_photos_qty             111047 non-null  float64
 23  product_weight_g               112632 non-null  float64
 24  product_length_cm              112632 non-null  float64
 25  product_height_cm              112632 non-null  float64
 26  product_width_cm               112632 non-null  float64
 27  seller_zip_code_prefix         112650 non-null  float64
 28  seller_city                    112650 non-null  str
 29  seller_state                   112650 non-null  str
 30  product_category_name_english  111023 non-null  str
dtypes: datetime64[us](6), float64(12), int64(1), str(12)
memory usage: 26.8 MB

Master Dataset Preview:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP,housewares
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,178.0,1.0,400.0,19.0,13.0,19.0,31570.0,belo horizonte,SP,perfumery
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,232.0,1.0,420.0,24.0,19.0,21.0,14840.0,guariba,SP,auto
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,...,468.0,3.0,450.0,30.0,10.0,20.0,31842.0,belo horizonte,MG,pet_shop
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,316.0,4.0,250.0,51.0,15.0,15.0,8752.0,mogi das cruzes,SP,stationery

======================================================================
PHASE 7 — CUSTOMER ANALYSIS
======================================================================

--- Customers by State ---
customer_state
SP    47820
RJ    14669
MG    13220
RS     6269
PR     5787
SC     4201
BA     3821
DF     2421
GO     2346
ES     2264
Name: count, dtype: int64

--- Customers by City ---
customer_city
sao paulo                17946
rio de janeiro            7885
belo horizonte            3167
brasilia                  2407
curitiba                  1762
campinas                  1669
porto alegre              1619
salvador                  1419
guarulhos                 1340
sao bernardo do campo     1070
Name: count, dtype: int64

======================================================================
PHASE 8 — CATEGORY ANALYSIS
======================================================================

--- Top 10 Categories by Revenue ---

   product_category_name_english  Orders  Items     Revenue
43                 health_beauty    8836   9670  1441248.07
70                 watches_gifts    5624   5991  1305541.61
7                 bed_bath_table    9417  11115  1241681.72
65                sports_leisure    7720   8641  1156656.48
15         computers_accessories    6689   7827  1059272.40
39               furniture_decor    6449   8334   902511.79
49                    housewares    5884   6964   778397.77
20                    cool_stuff    3632   3796   719329.95
5                           auto    3897   4235   685384.32
42                  garden_tools    3518   4347   584219.21

--- Top 10 Categories by Orders ---

   product_category_name_english  Orders  Items     Revenue
7                 bed_bath_table    9417  11115  1241681.72
43                 health_beauty    8836   9670  1441248.07
65                sports_leisure    7720   8641  1156656.48
15         computers_accessories    6689   7827  1059272.40
39               furniture_decor    6449   8334   902511.79
49                    housewares    5884   6964   778397.77
70                 watches_gifts    5624   5991  1305541.61
68                     telephony    4199   4545   394883.32
5                           auto    3897   4235   685384.32
69                          toys    3886   4117   561372.55

======================================================================
PHASE 9 — SELLER ANALYSIS
======================================================================

--- Top 10 Sellers ---

                             seller_id seller_state  Orders  Items    Revenue
857   4869f7a5dfa277a7dca6462dcf3b52b2           SP    1132   1156  249640.70
1535  7c67e1448b00f6e969d365cea6b010ab           SP     982   1364  239536.44
1013  53243585a1d6dc2643021fd1853d8905           BA     358    410  235856.68
881   4a3ca9315b744ce9f8e9374361493884           SP    1806   1987  235539.96
3024  fa1c13f2614d7b5c4749cbc52fecda94           SP     585    586  204084.73
2643  da8622b14eb17ae2831f4ac5b9dab84a           SP    1314   1551  185192.32
1560  7e93a43ef30c4f03f38b393420bc753a           SP     336    340  182754.05
192   1025f0e2d44d7041d6cf58b6550e0bfa           SP     915   1428  172860.69
1505  7a67c85e85bb2ce8582c35f2203ad736           SP    1160   1171  162648.38
1824  955fee9216a65b617aa5c0531780ce60           SP    1287   1499  160602.68

======================================================================
PHASE 10 — TIME SERIES ANALYSIS
======================================================================

--- Monthly Revenue ---

        Month     Revenue
0  2016-09-30      354.75
1  2016-10-31    56808.84
2  2016-11-30        0.00
3  2016-12-31       19.62
4  2017-01-31   137188.49
5  2017-02-28   286280.62
6  2017-03-31   432048.59
7  2017-04-30   412422.24
8  2017-05-31   586190.95
9  2017-06-30   502963.04
10 2017-07-31   584971.62
11 2017-08-31   668204.60
12 2017-09-30   720398.91
13 2017-10-31   769312.37
14 2017-11-30  1179143.77
15 2017-12-31   863547.23
16 2018-01-31  1107301.89
17 2018-02-28   986908.96
18 2018-03-31  1155126.82
19 2018-04-30  1159698.04
20 2018-05-31  1149781.82
21 2018-06-30  1022677.11
22 2018-07-31  1058728.03
23 2018-08-31  1003308.47
24 2018-09-30      166.46
25 2018-10-31        0.00

--- Monthly Orders ---

        Month  Orders
0  2016-09-30       4
1  2016-10-31     324
2  2016-11-30       0
3  2016-12-31       1
4  2017-01-31     800
5  2017-02-28    1780
6  2017-03-31    2682
7  2017-04-30    2404
8  2017-05-31    3700
9  2017-06-30    3245
10 2017-07-31    4026
11 2017-08-31    4331
12 2017-09-30    4285
13 2017-10-31    4631
14 2017-11-30    7544
15 2017-12-31    5673
16 2018-01-31    7269
17 2018-02-28    6728
18 2018-03-31    7211
19 2018-04-30    6939
20 2018-05-31    6873
21 2018-06-30    6167
22 2018-07-31    6292
23 2018-08-31    6512
24 2018-09-30      16
25 2018-10-31       4

Highest Revenue Month:

Month      2017-11-30 00:00:00
Revenue             1179143.77
Name: 14, dtype: object

======================================================================
PHASE 11 — PIVOT TABLES
======================================================================

--- State × Category Revenue Pivot ---

product_category_name_english,agro_industry_and_commerce,air_conditioning,art,arts_and_craftmanship,audio,auto,baby,bed_bath_table,books_general_interest,books_imported,...,security_and_services,signaling_and_security,small_appliances,small_appliances_home_oven_and_coffee,sports_leisure,stationery,tablets_printing_image,telephony,toys,watches_gifts
customer_state,,,,,,,,,,,,,,,,,,,,,
AC,0.00,0.00,0.00,0.0,0.00,661.91,871.97,725.21,757.51,0.00,...,0.0,0.00,100.91,0.00,2071.54,646.76,0.00,1271.43,318.05,1573.72
AL,1518.55,643.89,0.00,0.0,675.28,5367.78,1071.93,2831.85,162.87,0.00,...,0.0,0.00,0.00,0.00,4840.93,879.24,0.00,5267.91,1419.18,12762.76
AM,0.00,114.11,90.68,0.0,114.53,876.93,796.97,942.59,114.67,0.00,...,0.0,0.00,0.00,0.00,1732.14,869.01,72.85,1159.66,912.24,2152.09
AP,657.61,0.00,227.84,0.0,0.00,1406.68,0.00,879.89,0.00,0.00,...,0.0,0.00,0.00,0.00,1014.71,335.04,0.00,396.29,389.72,1846.92
BA,2494.48,979.95,1111.25,0.0,1695.59,34247.82,18353.65,32286.04,1324.93,93.98,...,0.0,868.82,4387.69,1717.69,46281.69,9021.78,617.99,25688.79,17747.78,53718.96

--- Payment Type × Order Status ---

payment_type  boleto  credit_card  debit_card  not_defined  voucher
order_status
approved           1            1           0            0        0
canceled         113          479           7            0       26
created            1            3           0            0        1
delivered      18358        71337        1429            2     5352
invoiced          69          217           4            0       24
processing        59          219           5            0       18
shipped          198          840          12            1       56
unavailable      130          430           8            0       41

======================================================================
PHASE 12 — STRING OPERATIONS
======================================================================

--- Categories containing 'bed' ---

    product_category_name_english
14                 bed_bath_table
273             furniture_bedroom

======================================================================
PHASE 13 — DELIVERY ANALYSIS
======================================================================

Average Delivery Days:
12.01

Fastest Delivery:
0.0

Slowest Delivery:
209.0

Delivery Statistics:

count    110196.000000
mean         12.007723
std           9.451455
min           0.000000
25%           6.000000
50%          10.000000
75%          15.000000
max         209.000000
Name: delivery_days, dtype: float64

======================================================================
PHASE 14 — FINAL BUSINESS QUESTIONS
======================================================================

Q1. Total Revenue:
15843553.24

Q2. Top Category by Revenue:
product_category_name_english    health_beauty
Orders                                    8836
Items                                     9670
Revenue                             1441248.07
Name: 43, dtype: object

Q3. Top Seller:
seller_id       4869f7a5dfa277a7dca6462dcf3b52b2
seller_state                                  SP
Orders                                      1132
Items                                       1156
Revenue                                 249640.7
Name: 857, dtype: object

Q4. Top State by Revenue:
customer_state
SP    5921678.12
RJ    2129681.98
MG    1856161.49
RS     885826.76
PR     800935.44
BA     611506.67
SC     610213.60
DF     353229.44
GO     347706.93
ES     324801.91
Name: revenue, dtype: float64

Q5. Average Order Value:
159.33

Q6. Most Common Payment Type:
credit_card

Q7. Payment Type by Total Value:
payment_type
credit_card    12542084.19
boleto          2869361.27
voucher          379436.87
debit_card       217989.79
not_defined           0.00
Name: payment_value, dtype: float64

Q8. Highest Revenue Month:
Month      2017-11-30 00:00:00
Revenue             1179143.77
Name: 14, dtype: object

Q9. Highest Order Month:
Month     2017-11-30 00:00:00
Orders                   7544
Name: 14, dtype: object

Q10. Category with Highest Average Item Price:
product_category_name_english
computers                                1098.340542
small_appliances_home_oven_and_coffee     624.285658
home_appliances_2                         476.124958
agro_industry_and_commerce                342.124858
musical_instruments                       281.616000
small_appliances                          280.778468
fixed_telephony                           225.693182
construction_tools_safety                 208.992371
watches_gifts                             201.135984
air_conditioning                          185.269226
Name: price, dtype: float64

Q11. State with Highest Average Order Value:
customer_state
PB    263.036959
AC    242.835802
AP    239.158824
AL    233.000969
RO    227.502055
PA    223.227805
TO    219.122929
RR    218.796087
PI    218.449051
RN    210.092948
Name: revenue, dtype: float64

Q12. Delivered Orders %:
97.02

Q13. Cancelled Orders %:
0.63

Q14. Average Delivery Time:
12.01

Q15. Categories with Longest Average Delivery:
product_category_name_english
office_furniture                     20.386691
christmas_supplies                   15.300000
security_and_services                15.000000
fashion_shoes                        14.933852
home_comfort_2                       14.066667
furniture_mattress_and_upholstery    13.891892
home_appliances_2                    13.424242
furniture_living_room                13.294949
fashion_underwear_beach              13.275591
garden_tools                         13.231959
Name: delivery_days, dtype: float64

======================================================================
PHASE 15 — EXPORTING FINAL REPORT
======================================================================

======================================================================
✅ PANDAS FINAL PROJECT COMPLETED
======================================================================

Generated files:
output/category_sales.csv
output/seller_sales.csv
output/monthly_sales.csv
output/monthly_orders.csv
output/state_revenue.csv
output/olist_analysis_report.xlsx