In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/employees.csv")

In [3]:
df.head()

   EmployeeID     Name Department        City  Experience  Salary  Performance
0         101    Alice         IT     Chennai           2   50000          4.5
1         102      Bob         HR  Coimbatore           5   65000          4.2
2         103  Charlie    Finance   Bangalore           7   72000          4.8
3         104    David         IT     Chennai           4   60000          4.1
4         105      Eva         HR     Madurai           3   55000          4.0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmployeeID   12 non-null     int64
 1   Name         12 non-null     str
 2   Department   12 non-null     str
 3   City         12 non-null     str
 4   Experience   12 non-null     int64
 5   Salary       12 non-null     int64
 6   Performance  12 non-null     float64
dtypes: float64(1), int64(3), str(3)
memory usage: 804.0 bytes

In [5]:
df.describe()

       EmployeeID  Experience        Salary  Performance
count   12.000000    12.00000     12.000000    12.000000
mean   106.500000     5.50000  67750.000000     4.416667
std      3.605551     2.54058  12263.211799     0.285509
min    101.000000     2.00000  50000.000000     4.000000
25%    103.750000     3.75000  59500.000000     4.200000
50%    106.500000     5.00000  66500.000000     4.350000
75%    109.250000     7.25000  72750.000000     4.625000
max    112.000000    10.00000  90000.000000     4.900000

In [6]:
df.isnull().sum()

EmployeeID     0
Name           0
Department     0
City           0
Experience     0
Salary         0
Performance    0
dtype: int64

In [7]:
pd.pivot_table(
    df,
    values="Salary",
    index="Department"
)

                  Salary
Department
Finance     83333.333333
HR          59333.333333
IT          61750.000000
Marketing   69000.000000

In [8]:
pd.pivot_table(
    df,
    values="Performance",
    index="Department"
)

            Performance
Department
Finance        4.800000
HR             4.133333
IT             4.375000
Marketing      4.350000

In [9]:
pd.pivot_table(
    df,
    values="Experience",
    index="Department"
)

            Experience
Department
Finance       8.666667
HR            4.000000
IT            3.750000
Marketing     6.500000

In [10]:
pd.pivot_table(
    df,
    values="Salary",
    index="City"
)

                  Salary
City
Bangalore   74666.666667
Chennai     59500.000000
Coimbatore  76000.000000
Madurai     61500.000000

In [12]:
salary_department = pd.pivot_table(
    df,
    values="Salary",
    index="Department"
)

salary_department.to_csv(
    "output/department_salary.csv"
)

In [14]:
pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    columns="City"
)

City        Bangalore  Chennai  Coimbatore  Madurai
Department
Finance       81000.0      NaN     88000.0      NaN
HR                NaN  58000.0     65000.0  55000.0
IT            62000.0  55000.0     75000.0      NaN
Marketing         NaN  70000.0         NaN  68000.0

In [15]:
pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    columns="City",
    fill_value=0
)

City        Bangalore  Chennai  Coimbatore  Madurai
Department
Finance       81000.0      0.0     88000.0      0.0
HR                0.0  58000.0     65000.0  55000.0
IT            62000.0  55000.0     75000.0      0.0
Marketing         0.0  70000.0         0.0  68000.0

In [16]:
pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc="sum"
)

            Salary
Department
Finance     250000
HR          178000
IT          247000
Marketing   138000

In [17]:
pd.pivot_table(
    df,
    values="EmployeeID",
    index="Department",
    aggfunc="count"
)

            EmployeeID
Department
Finance              3
HR                   3
IT                   4
Marketing            2

In [18]:
pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc="max"
)

            Salary
Department
Finance      90000
HR           65000
IT           75000
Marketing    70000

In [19]:
pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc="min"
)

            Salary
Department
Finance      72000
HR           55000
IT           50000
Marketing    68000

In [20]:
pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc=["mean","max","min"]
)

                    mean    max    min
                  Salary Salary Salary
Department
Finance     83333.333333  90000  72000
HR          59333.333333  65000  55000
IT          61750.000000  75000  50000
Marketing   69000.000000  70000  68000

In [21]:
pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    margins=True
)

                  Salary
Department
Finance     83333.333333
HR          59333.333333
IT          61750.000000
Marketing   69000.000000
All         67750.000000

In [22]:
pd.pivot_table(
    df,
    values=[
        "Salary",
        "Performance",
        "Experience"
    ],
    index="Department"
)

            Experience  Performance        Salary
Department
Finance       8.666667     4.800000  83333.333333
HR            4.000000     4.133333  59333.333333
IT            3.750000     4.375000  61750.000000
Marketing     6.500000     4.350000  69000.000000

In [23]:
dashboard = pd.pivot_table(
    df,
    values=[
        "Salary",
        "Performance",
        "Experience"
    ],
    index="Department"
)

dashboard.to_csv(
    "output/dashboard.csv"
)

In [24]:
dashboard = pd.pivot_table(
    df,
    values=[
        "Salary",
        "Performance",
        "Experience"
    ],
    index="Department"
)

dashboard.to_csv(
    "output/dashboard.csv"
)

In [25]:
pd.crosstab(
    df["Department"],
    df["City"],
    margins=True
)

City        Bangalore  Chennai  Coimbatore  Madurai  All
Department
Finance             2        0           1        0    3
HR                  0        1           1        1    3
IT                  1        2           1        0    4
Marketing           0        1           0        1    2
All                 3        4           3        2   12

In [26]:
pd.crosstab(
    df["Department"],
    df["City"],
    normalize=True
)

City        Bangalore   Chennai  Coimbatore   Madurai
Department
Finance      0.166667  0.000000    0.083333  0.000000
HR           0.000000  0.083333    0.083333  0.083333
IT           0.083333  0.166667    0.083333  0.000000
Marketing    0.000000  0.083333    0.000000  0.083333

In [27]:
pd.crosstab(
    df["Department"],
    df["City"],
    normalize="index"
)

City        Bangalore   Chennai  Coimbatore   Madurai
Department
Finance      0.666667  0.000000    0.333333  0.000000
HR           0.000000  0.333333    0.333333  0.333333
IT           0.250000  0.500000    0.250000  0.000000
Marketing    0.000000  0.500000    0.000000  0.500000

In [28]:
pd.pivot_table(
    df,
    values="Salary",
    index=["Department","City"]
)

                        Salary
Department City
Finance    Bangalore   81000.0
           Coimbatore  88000.0
HR         Chennai     58000.0
           Coimbatore  65000.0
           Madurai     55000.0
IT         Bangalore   62000.0
           Chennai     55000.0
           Coimbatore  75000.0
Marketing  Chennai     70000.0
           Madurai     68000.0

In [29]:
pd.pivot_table(
    df,
    values="Performance",
    index="Department",
    columns="City",
    aggfunc="mean",
    fill_value=0
)

City        Bangalore  Chennai  Coimbatore  Madurai
Department
Finance          4.85      0.0         4.7      0.0
HR               0.00      4.2         4.2      4.0
IT               4.30      4.3         4.6      0.0
Marketing        0.00      4.3         0.0      4.4

In [30]:
dashboard = pd.pivot_table(
    df,
    values=[
        "Salary",
        "Performance",
        "Experience"
    ],
    index="Department",
    aggfunc={
        "Salary":"mean",
        "Performance":"mean",
        "Experience":"mean"
    },
    margins=True
)

dashboard

            Experience  Performance        Salary
Department
Finance       8.666667     4.800000  83333.333333
HR            4.000000     4.133333  59333.333333
IT            3.750000     4.375000  61750.000000
Marketing     6.500000     4.350000  69000.000000
All           5.500000     4.416667  67750.000000

In [31]:
employee_count = pd.crosstab(
    df["Department"],
    df["City"],
    margins=True
)

In [32]:
dashboard.to_csv(
    "output/hr_dashboard.csv"
)

employee_count.to_csv(
    "output/employee_distribution.csv"
)